### ISSUE TITLE
1D tensor not supported in "sox_io" and new "soundfile" by save

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#1010]
`torchaudio.save` does not support 1D tensor with `sox_io` and the new `soundfile`. The error message is also inconsistent across backends.

- If we desire this restriction, let's document it in #903 and the docstring. However, this will become BC breaking once the default backend is changed.
- Otherwise, we could simply detect and `unsqueeze(0)` for 1D tensor.

Here's a code snippet to reproduce:
```python
>>> import torch
>>> import torchaudio
/private/home/vincentqb/anaconda3/envs/audio-pip/lib/python3.8/site-packages/torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(
>>> signal = torch.rand(2,16000)

>>> torchaudio.save('out.wav', signal[0], 16000)

>>> torchaudio.set_audio_backend("soundfile")
/private/home/vincentqb/anaconda3/envs/audio-pip/lib/python3.8/site-packages/torchaudio/backend/utils.py:63: UserWarning: The interface of "soundfile" backend is planned to change in 0.8.0 to match that of "sox_io" backend and the current interface will be removed in 0.9.0. To use the new interface, do `torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE = False` before setting the backend to "soundfile". Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(
>>> torchaudio.save('out.wav', signal[0], 16000)

>>> torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE = False
>>> torchaudio.set_audio_backend("soundfile")
>>> torchaudio.save('out.wav', signal[0], 16000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/vincentqb/anaconda3/envs/audio-pip/lib/python3.8/site-packages/torchaudio/backend/_soundfile_backend.py", line 166, in save
    raise ValueError(f"Expected 2D Tensor, got {src.ndim}D.")
ValueError: Expected 2D Tensor, got 1D.

>>> torchaudio.set_audio_backend("sox_io")
>>> torchaudio.save('out.wav', signal[0], 16000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/vincentqb/anaconda3/envs/audio-pip/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 174, in save
    torch.ops.torchaudio.sox_io_save_audio_file(filepath, signal, compression)
RuntimeError: Input tensor has to be 2D.
```

cc @mravanelli @mthrok

**Comment by vincentqb** [comment]
(potentially BC-breaking if sox_io becomes the default)
