### ISSUE TITLE
`compute_deltas` raising "CUDA error: invalid configuration argument" on large inputs

### ISSUE THREAD

**Issue by jcaw** [pytorch/audio#1103]
## 🐛 Bug

`torchaudio.functional.compute_deltas` is raising a `CUDA error: invalid configuration argument` when the batch size is too large.

## To Reproduce

1. On my GTX 970, calling `compute_deltas` with a large enough spectrogram and batch size triggers this error, e.g. `compute_deltas(torch.rand([64, 2, 1000, 1000], device="cuda"))`. 

Googling the other triggers for this error, it seems this is usually caused by exceeding the maximum CUDA block size (e.g. [here](https://github.com/pytorch/pytorch/issues/22526)). This varies by GPU.

Examples:

```python
>>> compute_deltas(torch.rand([64, 2, 1000, 1000], device="cuda"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jcaw/opt/miniconda3/envs/fastaudio-dev/lib/python3.7/site-packages/torchaudio/functional.py", line 1623, in compute_deltas
    specgram = torch.nn.functional.pad(specgram, (n, n), mode=mode)
  File "/home/jcaw/opt/miniconda3/envs/fastaudio-dev/lib/python3.7/site-packages/torch/nn/functional.py", line 3561, in _pad
    return torch._C._nn.replication_pad1d(input, pad)
RuntimeError: CUDA error: invalid configuration argument
```

This appears to be distinct from an outright out-of-memory error. If I push the parameters further:

```python
>>> compute_deltas(torch.rand([64, 2, 2000, 2000], device="cuda"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jcaw/opt/miniconda3/envs/fastaudio-dev/lib/python3.7/site-packages/torchaudio/functional.py", line 1623, in compute_deltas
    specgram = torch.nn.functional.pad(specgram, (n, n), mode=mode)
  File "/home/jcaw/opt/miniconda3/envs/fastaudio-dev/lib/python3.7/site-packages/torch/nn/functional.py", line 3561, in _pad
    return torch._C._nn.replication_pad1d(input, pad)
RuntimeError: CUDA out of memory. Tried to allocate 1.91 GiB (GPU 0; 3.95 GiB total capacity; 2.15 GiB already allocated; 518.06 MiB free; 2.39 GiB reserved in total by PyTorch)
```

Reducing the size of the input tensor solves the issue:

```python
>>> compute_deltas(torch.rand([32, 2, 1000, 1000], device="cuda"))
tensor(...)
>>> compute_deltas(torch.rand([64, 2, 500, 1000], device="cuda"))
tensor(...)
```

## Expected behavior

`compute_deltas` should return successfully (or explicitly produce an out-of-memory error, if that's the real issue).

## Environment

```
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.0.0
CMake version: version 3.19.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 970
Nvidia driver version: 455.45.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torch-audiomentations==0.4.0
[pip3] torchaudio==0.7.0
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl    anaconda
[conda] mkl                       2020.2                      256    anaconda
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0    anaconda
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] torch                     1.7.0                    pypi_0    pypi
[conda] torch-audiomentations     0.4.0                    pypi_0    pypi
[conda] torchaudio                0.7.0                    pypi_0    pypi
[conda] torchvision               0.8.1                    pypi_0    pypi
```

## Additional context

It appears to be CUDA-specific. I can't trigger this error on CPU.

**Comment by mthrok** [comment]
Hi @jcaw 

Thanks for the report and the detailed description. Looks like the fix should be applied in PyTorch, I will move the issue to PyTorch.
