### ISSUE TITLE
Building from source is failing for MacOS

### ISSUE THREAD

**Issue by AzizCode92** [pytorch/audio#1186]
## To Reproduce

Steps inside the documentation as described in the [README.md](https://github.com/pytorch/audio#from-source)

**Error Message:**
```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/Users//miniconda3/envs/audio/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users//Documents/side_projects/audio/build_tools/setup_helpers/extension.py", line 169, in build_extension
    super().build_extension(ext)
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users//miniconda3/envs/audio/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/Users//miniconda3/envs/audio/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
```

## Expected behavior
Successful build from source

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)? from source
 - If you are building from source, which commit is it?  107718c8feea52
 - What does `torchaudio.__version__` print? (If applicable) Not applicable

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): macOS 11.1 (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): `
BUILD_SOX=1 MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install`
 - Python version: 3.7
 - CUDA/cuDNN version: No cuda
 - GPU models and configuration: No GPU
 - Any other relevant information:

**Comment by mthrok** [comment]
Hi @AzizCode92 

Can you check if `ninja` is installed? You can install it with `pip install ninja`.
Also your PyTorch version 1.6.0 is very old, and I do not think it works with the latest commit.

**Comment by AzizCode92** [comment]
Hi @mthrok. 
I installed pytorch 1.7.1 and did `pip install ninja`.
Still the build is failing for me.

```
/Users//Documents/side_projects/audio/torchaudio/csrc/sox/register.cpp:5:24: error: unexpected namespace name 'torchaudio': expected expression
TORCH_LIBRARY_FRAGMENT(torchaudio, m) {
                       ^
/Users//Documents/side_projects/audio/torchaudio/csrc/sox/register.cpp:5:1: error: C++ requires a type specifier for all declarations
TORCH_LIBRARY_FRAGMENT(torchaudio, m) {
^
/Users//Documents/side_projects/audio/torchaudio/csrc/sox/register.cpp:5:36: error: use of undeclared identifier 'm'
TORCH_LIBRARY_FRAGMENT(torchaudio, m) {
                                   ^
/Users//Documents/side_projects/audio/torchaudio/csrc/sox/register.cpp:5:38: error: expected ';' after top level declarator
TORCH_LIBRARY_FRAGMENT(torchaudio, m) {
                                     ^
                                     ;
4 errors generated.
```

**Comment by mthrok** [comment]
@AzizCode92 Please try the nightly build of PyTorch. See pytorch.org for the installation.

**Comment by AzizCode92** [comment]
@mthrok thanks, that fixed the issue.
