### ISSUE TITLE
torch.jit.frontend.UnsupportedNodeError: ListComp aren't supported

### ISSUE THREAD

**Issue by siida36** [pytorch/audio#123]
Hi, I’m trying to use torchaudio with Python 3.6, torch 1.0.0 and CUDA-10.0.
I followed the README, but I get the error below:

```
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/asc/audio/torchaudio/__init__.py", line 7, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, legacy
  File "/root/asc/audio/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/root/asc/audio/torchaudio/functional.py", line 40, in <module>
    @torch.jit.script
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 689, in script
    ast = get_jit_ast(fn, is_method=False)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 147, in get_jit_ast
    return build_def(ctx, py_ast.body[0], type_line, is_method)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 182, in build_def
    build_stmts(ctx, body))
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 124, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 124, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 163, in __call__
    return method(ctx, node)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 312, in build_If
    build_stmts(ctx, stmt.body),
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 124, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 124, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 163, in __call__
    return method(ctx, node)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 245, in build_Assign
    rhs = build_expr(ctx, stmt.value)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 162, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: ListComp aren't supported
        fill_value (float): Value to fill in

    Outputs:
        Tensor: Padded/trimmed tensor
    """
    if max_len > tensor.size(len_dim):
        # array of [padding_left, padding_right, padding_top, padding_bottom]
        # so pad similar to append (aka only right/bottom) and do not pad
        # the length dimension. assumes equal sizes of padding.
        padding = [max_len - tensor.size(len_dim)
                   ~ <--- HERE
                   if (i % 2 == 1) and (i // 2 != len_dim)
                   else 0
                   for i in [0, 1, 2, 3]]
        # TODO add "with torch.no_grad():" back when JIT supports it
        tensor = torch.nn.functional.pad(tensor, padding, "constant", fill_value)
    elif max_len < tensor.size(len_dim):
        tensor = tensor.narrow(len_dim, 0, max_len)
    return tensor

```

How can I work it?

**Comment by jamarshon** [comment]
This is probably the same issue as https://github.com/pytorch/audio/issues/121. A fix should be created soon but you could build from commit d92de5b97fc6204db4b1e3ed20c03ac06f5d53f0 until then.

**Comment by 9bow** [comment]
I uninstalled and reinstall from commit as d92de5b as @jamarshon mentioned.
It works fine, and those who related in # 121 would like to refer to this.
Thanks, @jamarshon

**Comment by siida36** [comment]
@jamarshon
Thank you for reply!
I made a new docker container and retry, but I have same error...
My commands are below:

```
conda install pytorch=1.0.0 torchvision cudatoolkit=10.0 -c pytorch
git clone https://github.com/pytorch/audio
cd audio/
git reset d92de5b
apt-get update
apt-get install sox libsox-dev libsox-fmt-all
python setup.py install
```

@9bow
Would you like tell me your environment?

**Comment by 9bow** [comment]
@siida36 
First of all, I was experiencing an error related to #121, not the error you mentioned.

My environment is basically based on Deep Learning AMI for AWS EC2.
Specifically PyTorch 1.1, Cuda 10.0, Python 3.6.5, and Ubuntu 18.04 (LTS).
If there are any differences from the commands you provided, I used `git checkout`, uninstalled torchaudio and then reinstalled.

I hope this helps you.

**Comment by siida36** [comment]
@jamarshon, @9bow
I'm ashamed to forget `--hard` option of `git reset` command.
It works fine! Thank you!
