### ISSUE TITLE
Cant build from  source?

### ISSUE THREAD

**Issue by tyoc213** [pytorch/audio#1406]
## 🐛 Bug

I just cloned the repo and tried to build from source. Im geting this error after solving a problem about not cuda home not setup `export CUDA_HOME=/usr/local/cuda-11.2/` (not been able to calculate hash for nvrtc)

```
~/Documents/github/pytorch/audio [master|✔] 
01:29 $ pip install -e .
Obtaining file:///home/tyoc213/Documents/github/pytorch/audio
Requirement already satisfied: torch in /home/tyoc213/Documents/github/pytorch (from torchaudio==0.9.0a0+14dd917) (1.9.0a0+a61a8d0)
Requirement already satisfied: typing_extensions in /home/tyoc213/miniconda3/envs/xla/lib/python3.8/site-packages (from torch->torchaudio==0.9.0a0+14dd917) (3.7.4.3)
Requirement already satisfied: numpy in /home/tyoc213/miniconda3/envs/xla/lib/python3.8/site-packages (from torch->torchaudio==0.9.0a0+14dd917) (1.20.1)
Installing collected packages: torchaudio
  Running setup.py develop for torchaudio
    ERROR: Command errored out with exit status 1:
     command: /home/tyoc213/miniconda3/envs/xla/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/tyoc213/Documents/github/pytorch/audio/setup.py'"'"'; __file__='"'"'/home/tyoc213/Documents/github/pytorch/audio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/tyoc213/Documents/github/pytorch/audio/
    Complete output (164 lines):
    -- Building version 0.9.0a0+14dd917
    running develop
    running egg_info
    writing torchaudio.egg-info/PKG-INFO
    writing dependency_links to torchaudio.egg-info/dependency_links.txt
    writing requirements to torchaudio.egg-info/requires.txt
    writing top-level names to torchaudio.egg-info/top_level.txt
    reading manifest file 'torchaudio.egg-info/SOURCES.txt'
    writing manifest file 'torchaudio.egg-info/SOURCES.txt'
    running build_ext
    -- Caffe2: CUDA detected: 11.2
    -- Caffe2: CUDA nvcc is: /usr/local/cuda-11.2/bin/nvcc
    -- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.2
    -- Caffe2: Header version is: 11.2
    -- Found cuDNN: v8.1.0  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
    CMake Warning at /home/tyoc213/Documents/github/pytorch/torch/share/cmake/Caffe2/public/cuda.cmake:198 (message):
      Failed to compute shorthash for libnvrtc.so
    Call Stack (most recent call first):
      /home/tyoc213/Documents/github/pytorch/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
      /home/tyoc213/Documents/github/pytorch/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
      CMakeLists.txt:55 (find_package)
    
    
    -- Autodetected CUDA architecture(s):  8.6
    -- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
    Updated 3 paths from the index
    get_version.sh: 37: Bad substitution
    get_version.sh: The version number "5.5" specified in src/.version is not in MAJOR.MINOR format.
    get_version.sh: Stopping the construction of full version number from git history.
    get_version.sh: 45: [[: not found
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8
    [1/40] cd /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox && /usr/local/bin/cmake -E make_directory /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/CMakeFiles && /usr/local/bin/cmake -E touch /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/CMakeFiles/flac-complete && /usr/local/bin/cmake -E touch /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/flac-stamp/flac-done
    [2/40] cd /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox && /usr/local/bin/cmake -E make_directory /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/CMakeFiles && /usr/local/bin/cmake -E touch /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/CMakeFiles/amr-complete && /usr/local/bin/cmake -E touch /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/amr-stamp/amr-done
    [3/40] /usr/bin/clang++-8  -I../../third_party/kaldi/src -I../../third_party/kaldi/submodule/src -isystem /home/tyoc213/Documents/github/pytorch/torch/include -isystem /home/tyoc213/Documents/github/pytorch/torch/include/torch/csrc/api/include -isystem /usr/local/cuda-11.2/include -D_GLIBCXX_USE_CXX11_ABI=0 -Wall  -fvisibility=hidden -O3 -DNDEBUG -fPIC -std=gnu++14 -MD -MT third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/base/kaldi-math.cc.o -MF third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/base/kaldi-math.cc.o.d -o third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/base/kaldi-math.cc.o -c ../../third_party/kaldi/submodule/src/base/kaldi-math.cc
    [4/40] /usr/bin/clang++-8  -I../../third_party/kaldi/src -I../../third_party/kaldi/submodule/src -isystem /home/tyoc213/Documents/github/pytorch/torch/include -isystem /home/tyoc213/Documents/github/pytorch/torch/include/torch/csrc/api/include -isystem /usr/local/cuda-11.2/include -D_GLIBCXX_USE_CXX11_ABI=0 -Wall  -fvisibility=hidden -O3 -DNDEBUG -fPIC -std=gnu++14 -MD -MT third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/base/kaldi-error.cc.o -MF third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/base/kaldi-error.cc.o.d -o third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/base/kaldi-error.cc.o -c ../../third_party/kaldi/submodule/src/base/kaldi-error.cc
    [5/40] cd /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build && /usr/local/bin/cmake -P /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-stamp/vorbis-build-Release.cmake && /usr/local/bin/cmake -E touch /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-stamp/vorbis-build
    FAILED: third_party/sox/src/vorbis-stamp/vorbis-build
    cd /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build && /usr/local/bin/cmake -P /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-stamp/vorbis-build-Release.cmake && /usr/local/bin/cmake -E touch /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-stamp/vorbis-build
    CMake Error at /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-stamp/vorbis-build-Release.cmake:37 (message):
      Command failed: 2
    
       'make'
    
      See also
    
        /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-stamp/vorbis-build.log
    
    
    -- Log output is:
    make  all-recursive
    make[1]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build'
    Making all in m4
    make[2]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/m4'
    make[2]: Nothing to be done for 'all'.
    make[2]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/m4'
    Making all in include
    make[2]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/include'
    Making all in vorbis
    make[3]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/include/vorbis'
    make[3]: Nothing to be done for 'all'.
    make[3]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/include/vorbis'
    make[3]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/include'
    make[3]: Nothing to be done for 'all-am'.
    make[3]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/include'
    make[2]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/include'
    Making all in vq
    make[2]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/vq'
    make[2]: Nothing to be done for 'all'.
    make[2]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/vq'
    Making all in lib
    make[2]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib'
    Making all in modes
    make[3]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/modes'
    make[3]: Nothing to be done for 'all'.
    make[3]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/modes'
    Making all in books
    make[3]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books'
    Making all in coupled
    make[4]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books/coupled'
    make[4]: Nothing to be done for 'all'.
    make[4]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books/coupled'
    Making all in uncoupled
    make[4]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books/uncoupled'
    make[4]: Nothing to be done for 'all'.
    make[4]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books/uncoupled'
    Making all in floor
    make[4]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books/floor'
    make[4]: Nothing to be done for 'all'.
    make[4]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books/floor'
    make[4]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books'
    make[4]: Nothing to be done for 'all-am'.
    make[4]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books'
    make[3]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib/books'
    make[3]: Entering directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib'
      CCLD     test_sharedbook
    /usr/bin/ld: test_sharedbook-sharedbook.o: in function `_float32_pack':
    sharedbook.c:(.text+0x4d): undefined reference to `__log_finite'
    /usr/bin/ld: test_sharedbook-sharedbook.o: in function `_book_maptype1_quantvals':
    sharedbook.c:(.text+0x617): undefined reference to `__pow_finite'
    /usr/bin/ld: test_sharedbook-sharedbook.o: in function `_book_unquantize':
    sharedbook.c:(.text+0x88e): undefined reference to `__pow_finite'
    /usr/bin/ld: test_sharedbook-sharedbook.o: in function `vorbis_book_init_encode':
    sharedbook.c:(.text+0x1089): undefined reference to `__pow_finite'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[3]: *** [Makefile:573: test_sharedbook] Error 1
    make[3]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib'
    make[2]: *** [Makefile:660: all-recursive] Error 1
    make[2]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build/lib'
    make[1]: *** [Makefile:534: all-recursive] Error 1
    make[1]: Leaving directory '/home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-build'
    make: *** [Makefile:410: all] Error 2
    
    CMake Error at /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/vorbis-stamp/vorbis-build-Release.cmake:47 (message):
      Stopping after outputting logs.
    
    
    [6/40] cd /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src && /usr/local/bin/cmake -P /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/opusfile-stamp/opusfile-download-Release.cmake && /usr/local/bin/cmake -E touch /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/opusfile-stamp/opusfile-download
    -- opusfile download command succeeded.  See also /home/tyoc213/Documents/github/pytorch/audio/build/temp.linux-x86_64-3.8/third_party/sox/src/opusfile-stamp/opusfile-download-*.log
    [7/40] /usr/bin/clang++-8  -I../../third_party/kaldi/src -I../../third_party/kaldi/submodule/src -isystem /home/tyoc213/Documents/github/pytorch/torch/include -isystem /home/tyoc213/Documents/github/pytorch/torch/include/torch/csrc/api/include -isystem /usr/local/cuda-11.2/include -D_GLIBCXX_USE_CXX11_ABI=0 -Wall  -fvisibility=hidden -O3 -DNDEBUG -fPIC -std=gnu++14 -MD -MT third_party/kaldi/CMakeFiles/kaldi.dir/src/matrix/kaldi-vector.cc.o -MF third_party/kaldi/CMakeFiles/kaldi.dir/src/matrix/kaldi-vector.cc.o.d -o third_party/kaldi/CMakeFiles/kaldi.dir/src/matrix/kaldi-vector.cc.o -c ../../third_party/kaldi/src/matrix/kaldi-vector.cc
    [8/40] /usr/bin/clang++-8  -I../../third_party/kaldi/src -I../../third_party/kaldi/submodule/src -isystem /home/tyoc213/Documents/github/pytorch/torch/include -isystem /home/tyoc213/Documents/github/pytorch/torch/include/torch/csrc/api/include -isystem /usr/local/cuda-11.2/include -D_GLIBCXX_USE_CXX11_ABI=0 -Wall  -fvisibility=hidden -O3 -DNDEBUG -fPIC -std=gnu++14 -MD -MT third_party/kaldi/CMakeFiles/kaldi.dir/src/matrix/kaldi-matrix.cc.o -MF third_party/kaldi/CMakeFiles/kaldi.dir/src/matrix/kaldi-matrix.cc.o.d -o third_party/kaldi/CMakeFiles/kaldi.dir/src/matrix/kaldi-matrix.cc.o -c ../../third_party/kaldi/src/matrix/kaldi-matrix.cc
    [9/40] /usr/bin/clang++-8  -I../../third_party/kaldi/src -I../../third_party/kaldi/submodule/src -isystem /home/tyoc213/Documents/github/pytorch/torch/include -isystem /home/tyoc213/Documents/github/pytorch/torch/include/torch/csrc/api/include -isystem /usr/local/cuda-11.2/include -D_GLIBCXX_USE_CXX11_ABI=0 -Wall  -fvisibility=hidden -O3 -DNDEBUG -fPIC -std=gnu++14 -MD -MT third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/feat/feature-functions.cc.o -MF third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/feat/feature-functions.cc.o.d -o third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/feat/feature-functions.cc.o -c ../../third_party/kaldi/submodule/src/feat/feature-functions.cc
    [10/40] /usr/bin/clang++-8  -I../../third_party/kaldi/src -I../../third_party/kaldi/submodule/src -isystem /home/tyoc213/Documents/github/pytorch/torch/include -isystem /home/tyoc213/Documents/github/pytorch/torch/include/torch/csrc/api/include -isystem /usr/local/cuda-11.2/include -D_GLIBCXX_USE_CXX11_ABI=0 -Wall  -fvisibility=hidden -O3 -DNDEBUG -fPIC -std=gnu++14 -MD -MT third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/feat/pitch-functions.cc.o -MF third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/feat/pitch-functions.cc.o.d -o third_party/kaldi/CMakeFiles/kaldi.dir/submodule/src/feat/pitch-functions.cc.o -c ../../third_party/kaldi/submodule/src/feat/pitch-functions.cc
    ../../third_party/kaldi/submodule/src/feat/pitch-functions.cc:814:11: warning: unused variable 'full_frame_length' [-Wunused-variable]
        int32 full_frame_length = opts_.NccfWindowSize() + nccf_last_lag_;
              ^
    1 warning generated.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/tyoc213/Documents/github/pytorch/audio/setup.py", line 60, in <module>
        setup(
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/tyoc213/Documents/github/pytorch/audio/build_tools/setup_helpers/extension.py", line 54, in run
        super().run()
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/tyoc213/Documents/github/pytorch/audio/build_tools/setup_helpers/extension.py", line 108, in build_extension
        subprocess.check_call(
      File "/home/tyoc213/miniconda3/envs/xla/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tyoc213/miniconda3/envs/xla/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/tyoc213/Documents/github/pytorch/audio/setup.py'"'"'; __file__='"'"'/home/tyoc213/Documents/github/pytorch/audio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

## Environment

```
$ python ../torch/utils/collect_env.py 
Collecting environment information...
PyTorch version: 1.9.0a0+a61a8d0
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.19.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.142
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.39
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.9.0a0+a61a8d0
[pip3] torch-xla==1.9
[pip3] torchvision==0.9.0a0+7ffc952
[conda] numpy                     1.20.1                   pypi_0    pypi
[conda] torch                     1.9.0a0+a61a8d0           dev_0    <develop>
[conda] torch-xla                 1.9                       dev_0    <develop>
[conda] torchvision               0.9.0a0+7ffc952           dev_0    <develop>

```

And the log file

[vorbis-build.log](https://github.com/pytorch/audio/files/6187730/vorbis-build.log)

**Comment by vincentqb** [comment]
The instructions to build from source are given [here](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md). In particular, are you providing `BUILD_SOX=1` option?

**Comment by tyoc213** [comment]
@vincentqb I think I was able to compile locally torchaudio, but Im getting this

`RuntimeError: Error opening '/home/tyoc213/.cache/huggingface/datasets/downloads/extracted/__hash__/cv-corpus-6.1-2020-12-11/tr/clips/common_voice_tr_21921195.mp3': File contains data in an unknown format.`

While executing

`common_voice_train = common_voice_train.map(speech_file_to_array_fn, remove_columns=common_voice_train.column_names)`

**Comment by cpuhrsch** [comment]
There are currently issues with CUDA 11.x. Please see https://github.com/pytorch/pytorch/issues/51080

**Comment by tyoc213** [comment]
yep, I also tried to install from nightly, but it is only possible for torch1.9-cu112, if you add the audio or vision packages, they make it uninstall 1.9 and install a cpu 1.8 version with this `!pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu112/torch_nightly.html`, it install 1.9-cu112 if you only do `!pip install --pre torch  -f https://download.pytorch.org/whl/nightly/cu112/torch_nightly.html` but I need at less torchaudio.

https://github.com/pytorch/audio/issues/1047#issuecomment-804705183

**Comment by cpuhrsch** [comment]
cc @malfet @seemethere

**Comment by seemethere** [comment]
We are not currently building for CUDA 11.2 due to performance issues. Would you mind retrying this with the CUDA 11.1 binaries?

**Comment by tyoc213** [comment]
@seemethere do I need to install 11.1 drivers isn't? IIRC because I have a 3090 so compiled versions complains about sm85 not supported IIRC.

**Comment by tyoc213** [comment]
Well it seems that I don't need to uninstall drivers and install 11.1, seems to be working with `pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html`. So now I have an env to work.

But still if I want to compile correctly for the 11.2 driver without runtime errors https://github.com/pytorch/audio/issues/1406#issuecomment-805142263

What would I need to do?

**Comment by mthrok** [comment]
> `RuntimeError: Error opening '/home/tyoc213/.cache/huggingface/datasets/downloads/extracted/__hash__/cv-corpus-6.1-2020-12-11/tr/clips/common_voice_tr_21921195.mp3': File contains data in an unknown format.`

@tyoc213 If you are still encountering this issue, can you file a new issue?

**Comment by tyoc213** [comment]
Indeed is another different issue I think I passed too, my solution for the moment was to install the `pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html` as said above.

Still need to try again to compile from source.

**Comment by mthrok** [comment]
Please open a new issue if the problem persists.
