### ISSUE TITLE
Error when loading VCTK

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#143]
I'm getting an error from SOX when loading VCTK.

```
>>> import torchaudio
>>> torchaudio.datasets.VCTK("~/VCTK", download=True)
Downloading http://homepages.inf.ed.ac.uk/jyamagis/release/VCTK-Corpus.tar.gz
Processing...
Found 44257 audio files and 44085 utterences
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/vincentqb/anaconda3/envs/audiotutorial/lib/python3.7/site-packages/torchaudio-0.2-py3.7-linux-x86_64.egg/torchaudio/datasets/vctk.py", line 109, in __init__
    self.download()
  File "/private/home/vincentqb/anaconda3/envs/audiotutorial/lib/python3.7/site-packages/torchaudio-0.2-py3.7-linux-x86_64.egg/torchaudio/datasets/vctk.py", line 220, in download
    sig = read_audio(f, downsample=self.downsample)[0]
  File "/private/home/vincentqb/anaconda3/envs/audiotutorial/lib/python3.7/site-packages/torchaudio-0.2-py3.7-linux-x86_64.egg/torchaudio/datasets/vctk.py", line 39, in read_audio
    E = torchaudio.sox_effects.SoxEffects()
AttributeError: module 'torchaudio.sox_effects' has no attribute 'SoxEffects'
```

**Comment by rfalcon100** [comment]
Is this fix present in the stable version? I just installed the latest release, and I am still getting the same error:

```console
>>> import torchaudio
>>> import torchaudio.datasets as dsets
>>> b = dsets.VCTK('~/datasets/VCTK/', download=True)
Downloading http://homepages.inf.ed.ac.uk/jyamagis/release/VCTK-Corpus.tar.gz
Processing...
Found 44257 audio files and 44085 utterences
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/77/falconr1/unix/.conda/envs/audio/lib/python3.7/site-packages/torchaudio/datasets/vctk.py", line 109, in __init__
    self.download()
  File "/u/77/falconr1/unix/.conda/envs/audio/lib/python3.7/site-packages/torchaudio/datasets/vctk.py", line 220, in download
    sig = read_audio(f, downsample=self.downsample)[0]
  File "/u/77/falconr1/unix/.conda/envs/audio/lib/python3.7/site-packages/torchaudio/datasets/vctk.py", line 39, in read_audio
    E = torchaudio.sox_effects.SoxEffects()
AttributeError: module 'torchaudio.sox_effects' has no attribute 'SoxEffects'
```


My environment:
```console
(audio) ➜  ~ pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torchaudio in ./.conda/envs/audio/lib/python3.7/site-packages (0.2)
Requirement already satisfied: torch in ./.conda/envs/audio/lib/python3.7/site-packages (from torchaudio) (1.1.0)
Requirement already satisfied: numpy in ./.conda/envs/audio/lib/python3.7/site-packages (from torch->torchaudio) (1.16.4)
```

**Comment by jamarshon** [comment]
@rfalcon100 looks like you have v0.2.0 installed, you can check by printing `torchaudio.__version`. The fix is in v0.3.0.

**Comment by rfalcon100** [comment]
Oh, so the master branch is still v0.2.0 ?  To update I have to manually install v0.3.0 ?

**Comment by jamarshon** [comment]
what does torchaudio.__version print?

**Comment by rfalcon100** [comment]
I do have 0.2.0.

```console
>>> torchaudio.__version__
'0.2.0'
```

**Comment by jamarshon** [comment]
@rfalcon100 Okay so you can either wait for 0.3.0 binaries to come out or build from source (master or v0.3.0 as they are almost identical at this point of time). Let us know if you run into any issues
