### ISSUE TITLE
libtorchaudio C++ and transforms.MelSpectrogram

### ISSUE THREAD

**Issue by Ignasinou** [pytorch/audio#1818]
### 🐛 Describe the bug

Hey!

By following the [libtorchaudio](https://github.com/pytorch/audio/tree/master/examples/libtorchaudio) examples I have been able to successfully build and run them on macOS.

I've modified the augmentation python script in order to compute the MelSpectrograms of an audio .wav file. Here you can find the python script (based on the main.py from the augmentation example):

audio_wrapper.py:
```python3 
#!/usr/bin/env python3
"""
Create a data preprocess pipeline that can be run with libtorchaudio
"""
import os
import argparse

import torch
import torchaudio


class Pipeline(torch.nn.Module):
    """Example audio process pipeline.

    This example load waveform from a file then apply effects and save it to a file.
    """
    def __init__(self, rir_path: str):
        super().__init__()
        rir, sample_rate = torchaudio.load(rir_path)
        self.register_buffer('rir', rir)
        self.rir_sample_rate: int = sample_rate

    def forward(self, input_path: str, output_path: str):
        torchaudio.sox_effects.init_sox_effects()

        # 1. load audio
        waveform, sample_rate = torchaudio.load(input_path)

        # 2. Add background noise
        mel_spectrogram = torchaudio.transforms.MelSpectrogram(
            sample_rate=22050,
            n_fft=1024,
            hop_length=315,
            n_mels=80,
            f_max=8000,
            f_min=27.5
        )


def _create_jit_pipeline(rir_path, output_path):
    module = torch.jit.script(Pipeline(rir_path))
    print("*" * 40)
    print("* Pipeline code")
    print("*" * 40)
    print()
    print(module.code)
    print("*" * 40)
    module.save(output_path)


def _get_path(*paths):
    return os.path.join(os.path.dirname(__file__), *paths)


def _parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--rir-path",
        default=_get_path("..", "data", "rir.wav"),
        help="Audio dara for room impulse response."
    )
    parser.add_argument(
        "--output-path",
        default=_get_path("pipeline.zip"),
        help="Output JIT file."
    )
    return parser.parse_args()


def _main():
    args = _parse_args()
    _create_jit_pipeline(args.rir_path, args.output_path)


if __name__ == '__main__':
    _main()
```

When running the script from the terminal: `python3 audio_wrapper.py --rir-path "../data/rir.wav" --output-path "./pipeline.zip"`. The following error appears:

```
Traceback (most recent call last):
  File "audio_wrapper.py", line 76, in <module>
    _main()
  File "audio_wrapper.py", line 72, in _main
    _create_jit_pipeline(args.rir_path, args.output_path)
  File "audio_wrapper.py", line 41, in _create_jit_pipeline
    module = torch.jit.script(Pipeline(rir_path))
  File "/Users/ignasinou/miniconda3/lib/python3.7/site-packages/torch/jit/_script.py", line 1097, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/Users/ignasinou/miniconda3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 412, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/Users/ignasinou/miniconda3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 478, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/Users/ignasinou/miniconda3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 355, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/Users/ignasinou/miniconda3/lib/python3.7/site-packages/torch/jit/annotations.py", line 134, in check_fn
    loc, f"Cannot instantiate class '{py_ast.body[0].name}' in a script function")
torch.jit.frontend.FrontendError: Cannot instantiate class 'MelSpectrogram' in a script function:
  File "audio_wrapper.py", line 30
    
        # 2. Add background noise
        mel_spectrogram = torchaudio.transforms.MelSpectrogram(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            sample_rate=22050,
            n_fft=1024,
 ```
 
The audio file seems to be loaded correctly but why it cannot instantiate the MelSpectrogram class? 

Best.

### Versions

```
PyTorch version: 1.9.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 11.0.3 (clang-1103.0.32.62)
CMake version: version 3.20.5
Libc version: N/A

Python version: 3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)] (64-bit runtime)
Python platform: Darwin-19.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.9.1
[pip3] torchaudio==0.9.1
[conda] numpy                     1.20.2                   pypi_0    pypi
[conda] torch                     1.9.1                    pypi_0    pypi
[conda] torchaudio                0.9.1                    pypi_0    pypi

```

**Comment by mthrok** [comment]
Hi @Ignasinou 

Thanks for trying the C++ example. Regarding the error, your code is instantiating a transform object in `forward` function,  this is not TorchScript-able.

A correct way is to instantiate the transform in `__init__`, then use the transform in `forward`.

```python
class Pipeline(torch.nn.Module):
    def __init__(self, ...):
        ...
        self.mel_spec = torchaudio.transforms.MelSpectrogram(...)

    def forward(self, ...):
        ...
        # apply Mel spectrogram
        mel_spec = self.mel_spec(waveform)
```

**Comment by Ignasinou** [comment]
Thanks for the quick reply. 
Yes, it works now, next time I will have to pay a bit more attention. 

Thanks again. 
I'm closing the issue!
