### ISSUE TITLE
CI for Python 2

### ISSUE THREAD

**Issue by ezyang** [pytorch/audio#200]
torchaudio is currently broken on Python 2 with

```
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ezyang/Library/Python/2.7/lib/python/site-packages/torchaudio/__init__.py", line 8, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, compliance, _docs
  File "/Users/ezyang/Library/Python/2.7/lib/python/site-packages/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/Users/ezyang/Library/Python/2.7/lib/python/site-packages/torchaudio/functional.py", line 242, in <module>
    @torch.jit.script
  File "/usr/local/lib/python2.7/site-packages/torch/jit/__init__.py", line 1159, in script
    ast = get_jit_def(obj)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 166, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 206, in build_def
    build_stmts(ctx, body))
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 122, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 182, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 274, in build_Assign
    rhs = build_expr(ctx, stmt.value)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 182, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 521, in build_IfExp
    build_expr(ctx, expr.orelse))
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 182, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 477, in build_BinOp
    rhs = build_expr(ctx, expr.right)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 182, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 430, in build_Call
    args = [build_expr(ctx, py_arg) for py_arg in expr.args]
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 182, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 477, in build_BinOp
    rhs = build_expr(ctx, expr.right)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 182, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python2.7/site-packages/torch/jit/frontend.py", line 481, in build_BinOp
    raise RuntimeError('Division of ints in JIT script uses Python 3 true '
RuntimeError: Division of ints in JIT script uses Python 3 true division semantics. Please put `from __future__ import division` at the top of your file

```

I'll fix this error, but we need to turn on Py2 CI to catch occurrences of this in the future. (Or officially drop support for Py2)

**Comment by ezyang** [comment]
fixed in a424509dda5b57c932fa8b5b780de93e60ed7ee2
