### ISSUE TITLE
TemporaryDirectory is not Python 2 compatible

### ISSUE THREAD

**Issue by ezyang** [pytorch/audio#202]
```
macbook-pro-116:audio ezyang$ python test/test_transforms.py 
Traceback (most recent call last):
  File "test/test_transforms.py", line 19, in <module>
    class Tester(unittest.TestCase):
  File "test/test_transforms.py", line 29, in Tester
    test_dirpath, test_dir = common_utils.create_temp_assets_dir()
  File "/Users/ezyang/Dev/audio/test/common_utils.py", line 15, in create_temp_assets_dir
    tmp_dir = tempfile.TemporaryDirectory()
AttributeError: 'module' object has no attribute 'TemporaryDirectory'
```

**Comment by ezyang** [comment]
Fixed in a424509dda5b57c932fa8b5b780de93e60ed7ee2
