### ISSUE TITLE
Can't import torchaudio?

### ISSUE THREAD

**Issue by FireWizard312** [pytorch/audio#2035]
### 🐛 Describe the bug

I downloaded torchaudio on the M1 mac using pip, but when I try to import it in Python, I'm greeted with this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mliu/asdf/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension  # noqa: F401
  File "/Users/mliu/asdf/lib/python3.8/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/Users/mliu/asdf/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 11, in _init_extension
    _init_script_module(ext)
  File "/Users/mliu/asdf/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
  File "/Users/mliu/asdf/lib/python3.8/site-packages/torch/_classes.py", line 48, in load_library
    torch.ops.load_library(path)
  File "/Users/mliu/asdf/lib/python3.8/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/mliu/asdf/lib/python3.8/site-packages/torchaudio/_torchaudio.so, 6): Symbol not found: __Z16THPVariable_WrapN2at6TensorE
  Referenced from: /Users/mliu/asdf/lib/python3.8/site-packages/torchaudio/_torchaudio.so
  Expected in: /Users/mliu/asdf/lib/python3.8/site-packages/torch/lib/libtorch_python.dylib
 in /Users/mliu/asdf/lib/python3.8/site-packages/torchaudio/_torchaudio.so

The code I ran was just import torchaudio
Is there a way to fix this?

### Versions

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.9 (default, Aug  3 2021, 19:21:54)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-11.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.10.0
[pip3] torchvision==0.10.0
[conda] Could not collect

**Comment by mthrok** [comment]
Hi @FireWizard312 

Looking at the log, something about the Python environment seems to be mixed up. There are Python ends from `/Users` and `/Applications`. 
Could you tell how you installed it?

**Comment by FireWizard312** [comment]
Never mind, I was simply using the wrong Python version on Visual Studio Code. After installing it through conda and changing my version of Python, it ran fine.
