### ISSUE TITLE
Segfault in `torchaudio.transforms.Spectrogram` with a multi-GPU setup

### ISSUE THREAD

**Issue by scarecrow1123** [pytorch/audio#241]
## 🐛 Bug
`torchaudio.transforms.Spectrogram` consistently gets into a segfault when used in a multi-GPU DataParallel setup. However I can confirm that it works consistently well when run on a single GPU.

Below is the gdb trace:

```
#0  0x00007fffbbee4c61 in std::_Hashtable<std::reference_wrapper<at::native::detail::CuFFTParams>, std::pair<std::reference_wrapper<at::native::detail::CuFFTParams> const, std::_List_iterator<std::pair<at::native::detail::CuFFTParams, at::native::detail::CuFFTConfig> > >, std::allocator<std::pair<std::reference_wrapper<at::native::detail::CuFFTParams> const, std::_List_iterator<std::pair<at::native::detail::CuFFTParams, at::native::detail::CuFFTConfig> > > >, std::__detail::_Select1st, at::native::ParamsEqual<at::native::detail::CuFFTParams>, at::native::ParamsHash<at::native::detail::CuFFTParams>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node(unsigned long, std::reference_wrapper<at::native::detail::CuFFTParams> const&, unsigned long) const () from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so
#1  0x00007fffbbee5194 in at::native::detail::CuFFTConfig const& at::native::detail::CuFFTParamsLRUCache::try_emplace_value<at::native::detail::CuFFTParams, at::Tensor&, long&, bool&, bool&, c10::ArrayRef<long>&, bool&, c10::ArrayRef<long>&>(at::native::detail::CuFFTParams&&, at::Tensor&, long&, bool&, bool&, c10::ArrayRef<long>&, bool&, c10::ArrayRef<long>&) () from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so
#2  0x00007fffbbee0ddf in at::native::_fft_cufft(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>) ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so
#3  0x00007fffba7c49df in at::CUDAType::_fft_with_size(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>) const ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so
#4  0x00007fffb3ce8e72 in torch::autograd::VariableType::_fft_with_size(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>) const () from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libtorch.so.1
#5  0x00007fffb6b3a6df in at::native::_fft(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool) ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2.so
#6  0x00007fffb6b3b702 in at::native::rfft(at::Tensor const&, long, bool, bool) ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2.so
#7  0x00007fffb6e34cb5 in at::TypeDefault::rfft(at::Tensor const&, long, bool, bool) const ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2.so
#8  0x00007fffb3f0f886 in torch::autograd::VariableType::rfft(at::Tensor const&, long, bool, bool) const ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libtorch.so.1
#9  0x00007fffb6b3cfea in at::native::stft(at::Tensor const&, long, c10::optional<long>, c10::optional<long>, at::Tensor const&, bool, bool) ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2.so
#10 0x00007fffb6e2eabe in at::TypeDefault::stft(at::Tensor const&, long, c10::optional<long>, c10::optional<long>, at::Tensor const&, bool, bool) const ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libcaffe2.so
#11 0x00007fffb3f1175a in torch::autograd::VariableType::stft(at::Tensor const&, long, c10::optional<long>, c10::optional<long>, at::Tensor const&, bool, bool) const ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libtorch.so.1
#12 0x00007fffe525eb8c in torch::autograd::THPVariable_stft(_object*, _object*, _object*) ()
from /home/seelan/anaconda3/envs/asr_latest/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#13 0x0000555555665c54 in _PyCFunction_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Objects/methodobject.c:231
#14 0x00005555556edabc in call_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4851
#15 0x000055555571075a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3335
#16 0x00005555556e6e66 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4166
#17 0x00005555556e7ed6 in fast_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4992
#18 0x00005555556edb95 in call_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4872
#19 0x000055555571151c in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3351
#20 0x00005555556e7c5b in _PyFunction_FastCall (globals=<optimized out>, nargs=8, args=<optimized out>, co=<optimized out>)
#21 fast_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4968
#22 0x00005555556edb95 in call_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4872
#23 0x000055555571075a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3335
#24 0x00005555556e82db in _PyFunction_FastCall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>)
at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4933
#25 _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5035
#26 0x000055555566601f in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2310
#27 0x000055555566aaa3 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2373
#28 0x0000555555665a5e in PyObject_Call () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2261
#29 0x0000555555711e37 in do_call_core (kwdict=0x7fff43b3c3f0, callargs=0x7fff43b58c50, func=0x7fff50ceaf48)
at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5120
#30 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3404
#31 0x00005555556e6e66 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4166
#32 0x00005555556e837e in _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5084
#33 0x000055555566601f in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2310
#34 0x000055555566aaa3 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2373
#35 0x0000555555665a5e in PyObject_Call () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2261
#36 0x00005555556bf371 in slot_tp_call () at /tmp/build/80754af9/python_1564510748219/work/Objects/typeobject.c:6207
#37 0x0000555555665e3b in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2331
#38 0x00005555556edc0e in call_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4875
#39 0x000055555571075a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3335
#40 0x00005555556e729e in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4166
#41 0x00005555556e8598 in _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5084
#42 0x000055555566601f in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2310
#43 0x000055555566aaa3 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2373
#44 0x0000555555665a5e in PyObject_Call () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2261
#45 0x0000555555711e37 in do_call_core (kwdict=0x7fff43b3c5e8, callargs=0x7ffff7f91048, func=0x7fff555fba88)
at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5120
#46 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3404
#47 0x00005555556e6e66 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4166
#48 0x00005555556e8598 in _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5084
#49 0x000055555566601f in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2310
#50 0x000055555566aaa3 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2373
#51 0x0000555555665a5e in PyObject_Call () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2261
#52 0x00005555556bf371 in slot_tp_call () at /tmp/build/80754af9/python_1564510748219/work/Objects/typeobject.c:6207
#53 0x0000555555665a5e in PyObject_Call () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2261
#54 0x0000555555711e37 in do_call_core (kwdict=0x7fff43b3cca8, callargs=0x7ffff7f91048, func=0x7fff43b3a198)
at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5120
#55 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3404
#56 0x00005555556e8ff6 in _PyEval_EvalCodeWithName (qualname=0x0, name=0x0, closure=0x7fff44d5ffc0, kwdefs=0x0, defcount=1, defs=0x7fffa0277990, kwstep=2,
    kwcount=<optimized out>, kwargs=0x7ffff7f91068, kwnames=0x7ffff7f91060, argcount=<optimized out>, args=0x7ffde0000c70, locals=0x0, globals=<optimized out>,
    _co=0x7fffa0276b70) at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4166
#57 PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4187
#58 0x00005555556e98e6 in function_call () at /tmp/build/80754af9/python_1564510748219/work/Objects/funcobject.c:604
#59 0x0000555555665a5e in PyObject_Call () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2261
#60 0x0000555555711e37 in do_call_core (kwdict=0x7fff43badd38, callargs=0x7fff4c14ebf8, func=0x7fff43b62b70)
at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5120
#61 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3404
#62 0x00005555556e7c5b in _PyFunction_FastCall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4933
#63 fast_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4968
#64 0x00005555556edb95 in call_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4872
#65 0x000055555571075a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3335
#66 0x00005555556e7c5b in _PyFunction_FastCall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4933
#67 fast_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4968
#68 0x00005555556edb95 in call_function () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4872
#69 0x000055555571075a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:3335
#70 0x00005555556e82db in _PyFunction_FastCall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:4933
#71 _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Python/ceval.c:5035
#72 0x000055555566601f in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2310
#73 0x000055555566aaa3 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2373
#74 0x0000555555665a5e in PyObject_Call () at /tmp/build/80754af9/python_1564510748219/work/Objects/abstract.c:2261
#75 0x0000555555763976 in t_bootstrap () at /tmp/build/80754af9/python_1564510748219/work/Modules/_threadmodule.c:1000
#76 0x00005555557175f8 in pythread_wrapper (arg=<optimized out>) at /tmp/build/80754af9/python_1564510748219/work/Python/thread_pthread.h:205
#77 0x00007ffff7bc16ba in start_thread (arg=0x7ffecccaa700) at pthread_create.c:333
#78 0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)?
pip
 - If you are building from source, which commit is it?
NA
 - What does `torchaudio.__version__` print? (If applicable)
0.2.0

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): NA
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.0.130/7501
 - GPU models and configuration: 2080Ti
 - Any other relevant information:

**Comment by jamarshon** [comment]
@scarecrow1123 could we have a small code snippet where this error would occur?
