### ISSUE TITLE
Save signal with AMR-NB format

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/audio#251]
Conversion with `sox input.wav -r 8k ouptut.amr-nb` command works fine, `libsox-fmt-all` is installed.

```python
# saving to GSM works:
torchaudio.save('output.gsm', signal, 8000)

# saving to AMR-NB does not:
torchaudio.save('output.amr-nb', signal, 8000)
#formats: no handler for given file type `amr-nb'
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/miniconda/lib/python3.7/site-packages/torchaudio/__init__.py", line 133, in save
#    return save_encinfo(filepath, src, channels_first, si)
#  File "/miniconda/lib/python3.7/site-packages/torchaudio/__init__.py", line 202, in save_encinfo
#    _torch_sox.write_audio_file(filepath, src, signalinfo, encodinginfo, filetype)
#RuntimeError: Error writing audio file: could not open file for writing
```

**Comment by vadimkantorov** [comment]
It seems that somehow AMR-NB was not present at torchaudio compile-time
