### ISSUE TITLE
On manual install, some models and datasets do not get installed/downloaded

### ISSUE THREAD

**Issue by surak** [pytorch/audio#2642]
### 🐛 Describe the bug

When installing by hand, I try to run the examples of torch audio and I run into issues like this:

```python
$ python examples/pipeline_wavernn/main.py
Traceback (most recent call last):
  File "/p/project/audio/examples/pipeline_wavernn/main.py", line 16, in <module>
    from torchaudio.datasets.utils import bg_iterator
ImportError: cannot import name 'bg_iterator' from 'torchaudio.datasets.utils' (/p/project/software/torchaudio/0.11.0-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/torchaudio/datasets/utils.py)
```

or

```python
python examples/tutorials/audio_data_augmentation_tutorial.py 
1.11
0.11.0+820b383
Traceback (most recent call last):
  File "/p/project//audio/examples/tutorials/audio_data_augmentation_tutorial.py", line 33, in <module>
    from torchaudio.utils import download_asset
ImportError: cannot import name 'download_asset' from 'torchaudio.utils' (/p/project/software/torchaudio/0.11.0-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/torchaudio/utils/__init__.py)
```

or

```python
python asr_inference_with_ctc_decoder_tutorial.py 
1.11
0.11.0+820b383
Traceback (most recent call last):
  File "/p/project/audio/examples/tutorials/asr_inference_with_ctc_decoder_tutorial.py", line 65, in <module>
    from torchaudio.models.decoder import ctc_decoder
ModuleNotFoundError: No module named 'torchaudio.models.decoder'
```

So it seems that the install is either not complete or these codes in the example folder need something more, which I am failing to see.

### Versions

This is PyTorch 0.11.0, as the institute is using PyTorch 1.11 on the A100 GPUs.

**Comment by carolineechen** [comment]
Hi @surak, thanks for this issue.
- `bg_iterator` has been deprecated as of torchaudio 0.11, which is the reason for the first ImportError. Thanks for bringing this up, I'll push out a fix for the example(s) using it.
- `download_asset` and `torchaudio.models.decoder` were only added in release 0.12, so the version of PyTorch and TorchAudio you have are not compatible with those examples.
