### ISSUE TITLE
torchaudio.sox_effects.apply_effects_file broken in 0.12.1

### ISSUE THREAD

**Issue by rbracco** [pytorch/audio#2760]
### 🐛 Describe the bug

I have previously used this function to load audio and apply temporal effects, but upon upgrading to torch 1.12.1 and torchaudio 0.12.1 it no longer works. I stepped through in the debugger and `ret = torch.ops.torchaudio.sox_effects_apply_effects_file(path, effects, normalize, channels_first, format)` returns None. I am 100% sure the path is correct as `torchaudio.load(path)` correctly returns a tensor. 

There may be a wider issue as I found a similar comment from Dr. Scott Hawley at the bottom of #2363 (this issue is unrelated to the current bug), but this also could just be the result of a colab specific quirk. Thank you. 

```
2022-10-12 09:23:52.913 Uncaught app exception
Traceback (most recent call last):
  File "/home/rob/.cache/pypoetry/virtualenvs/traindata-xtjSOPgv-py3.8/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "/home/rob/code/traindata/traindata/speechdata/streamlit/streamlit_models.py", line 268, in <module>
    main()
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/rob/code/traindata/traindata/speechdata/streamlit/streamlit_models.py", line 260, in main
    _model_detail_view()
  File "/home/rob/code/traindata/traindata/speechdata/streamlit/streamlit_models.py", line 79, in _model_detail_view
    audio_paginator(display_audio_file, afs, items_per_page=5)
  File "/home/rob/code/traindata/traindata/speechdata/streamlit/paginator.py", line 69, in audio_paginator
    func(i, item)
  File "/home/rob/code/traindata/traindata/speechdata/streamlit/streamlit_models.py", line 129, in display_audio_file
    play_audio(full_path, speed="1.0", format="mp3")
  File "/home/rob/code/traindata/traindata/speechdata/streamlit/play_audio.py", line 13, in play_audio
    aud, sr = torchaudio.sox_effects.apply_effects_file(filename, effects=effects)
  File "/home/rob/.cache/pypoetry/virtualenvs/traindata-xtjSOPgv-py3.8/lib/python3.8/site-packages/torchaudio/sox_effects/sox_effects.py", line 283, in apply_effects_file
    if ret is not None:
RuntimeError: Failed to load audio from /home/rob/code/data/voxforge/audios/nestea247-b0227.mp3
```

### Versions

PyTorch version: 1.12.1+cu116
OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.29
[pip3] torch==1.12.1+cu116
[pip3] torchaudio==0.12.1+cu116

**Comment by rbracco** [comment]
Oops, looks like this is a duplicate of #2691 which remains open
