### ISSUE TITLE
RuntimeError: Failed to fetch metadata from sample3.mp3 on Version 0.12.1 of TorchAudio

### ISSUE THREAD

**Issue by qanastek** [pytorch/audio#2765]
### 🐛 Describe the bug

Dear maintainers,

I update to the last LTS (`0.12.1`) version of `torchaudio` and using `torchaudio.info` raise exceptions now when loading metadata for MP3 files. I downgrade to `0.11.0` and `0.10.0` and both are working well.

**The following example return the exceptions :**

```bash
wget https://filesamples.com/samples/audio/mp3/sample3.mp3
```

```python
import torchaudio
print(torchaudio.info("sample3.mp3"))
```

**Error (`0.12.1`) :**

```plain
Traceback (most recent call last):
  File "TestSox.py", line 8, in <module>
    r = torchaudio.info(mp3_path)
  File "/users/ylabrak/.conda/envs/SpeechBrain/lib/python3.7/site-packages/torchaudio/backend/sox_io_backend.py", line 104, in info
    return _fallback_info(filepath, format)
  File "/users/ylabrak/.conda/envs/SpeechBrain/lib/python3.7/site-packages/torchaudio/backend/sox_io_backend.py", line 13, in _fail_info
    raise RuntimeError("Failed to fetch metadata from {}".format(filepath))
RuntimeError: Failed to fetch metadata from sample3.mp3
```

**Normal output (`0.11.0` and `0.10.0` ) :**

```python
AudioMetaData(sample_rate=44100, num_frames=4666750, num_channels=2, bits_per_sample=0, encoding=MP3)
```

### Versions

**Bad environment :**

`pip install torchaudio==0.12.1`

```plain
Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2
Libc version: glibc-2.10

Python version: 3.7.10 (default, Feb 26 2021, 18:47:35)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-73-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.2.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.0
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.9.1+cu102
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torchaudio                0.12.1                   pypi_0    pypi
[conda] torchvision               0.9.1+cu102              pypi_0    pypi

```

**Working environment :**

`pip install torchaudio==0.10.0` or `pip install torchaudio==0.11.0`

```plain

Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2
Libc version: glibc-2.10

Python version: 3.7.10 (default, Feb 26 2021, 18:47:35)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-73-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.2.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.0
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.9.1+cu102
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.9.1+cu102              pypi_0    pypi
```

**Comment by nateanl** [comment]
Hi @qanastek, mp3 metadata fetch and decoding are handled by FFMpeg in version 12.1. Therefore you need to install it from conda to fetch metadata for your mp3 file.

**Comment by nateanl** [comment]
Closed the issue. Feel free to reopen it if you still meet the issue.
