### ISSUE TITLE
Build issue: socket.gaierror: [Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/audio#2807]
### 🐛 Describe the bug

I'm trying to install TorchAudio 0.13.0 from source but I encounter the following build error:
```
  Traceback (most recent call last):
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/urllib/request.py", line 1346, in do_open
      h.request(req.get_method(), req.selector, req.data, headers,
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/http/client.py", line 1285, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/http/client.py", line 1331, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/http/client.py", line 1280, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/http/client.py", line 1040, in _send_output
      self.send(msg)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/http/client.py", line 980, in send
      self.connect()
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/http/client.py", line 1447, in connect
      super().connect()
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/http/client.py", line 946, in connect
      self.sock = self._create_connection(
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/socket.py", line 823, in create_connection
      for res in getaddrinfo(host, port, 0, SOCK_STREAM):
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/socket.py", line 954, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
See below for the full build log:

* [build log](https://github.com/pytorch/audio/files/9892698/spack-build-out.txt)

Has anyone seen anything like this before?

### Versions

Script doesn't run on my system (I don't have pip installed), but here are some commonly requested versions:

* PyTorch: 1.13.0
* Python: 3.9.13
* CUDA: N/A
* ROCm: N/A
* macOS: 12.6.1
* Apple Clang: 14.0.0

**Comment by mthrok** [comment]
Looks like network issue. Can you download https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.3.tar.gz and put it in `third_party/archives/libogg-1.3.3.tar.gz`?

**Comment by adamjstewart** [comment]
Looks like it was a transient network issue, it's working fine now. Sorry for the noise!
