### ISSUE TITLE
dtype mismatch when using amp for HuBERT pre-training

### ISSUE THREAD

**Issue by pyf98** [pytorch/audio#2847]
### 🐛 Describe the bug

I tried to pre-train the HuBERT model with automatic mixed precision `amp`. I made two changes to enable amp training:

First, I added a new argument in [`_parse_args`](https://github.com/pytorch/audio/blob/main/examples/hubert/train.py#L82) for precision:
```
parser.add_argument(
        "--precision",
        default=32,
        type=int,
        choices=[16, 32],
        help="Precision for training, 16: half precision with amp."
    )
```

Then, I passed the argument to the [`Trainer`](https://github.com/pytorch/audio/blob/main/examples/hubert/train.py#L51):
```
trainer = Trainer(
        default_root_dir=args.exp_dir,
        max_steps=args.max_updates,
        num_nodes=args.num_nodes,
        gpus=args.gpus,
        accelerator="gpu",
        strategy="ddp",
        replace_sampler_ddp=False,
        callbacks=callbacks,
        reload_dataloaders_every_n_epochs=1,
        precision=args.precision,
    )
```

But it gave this error:
```
Traceback (most recent call last):
  File "/usr0/home/yifanpen/torchaudio_examples/hubert/train.py", line 223, in <module>
    cli_main()
  File "/usr0/home/yifanpen/torchaudio_examples/hubert/train.py", line 219, in cli_main
    run_train(args)
  File "/usr0/home/yifanpen/torchaudio_examples/hubert/train.py", line 80, in run_train
    trainer.fit(model, ckpt_path=args.resume_checkpoint)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1153, in _run_train
    self._run_sanity_check()
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1225, in _run_sanity_check
    val_loop.run()
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 360, in validation_step
    return self.model(*args, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/pytorch_lightning/overrides/base.py", line 110, in forward
    return self._forward_module.validation_step(*inputs, **kwargs)
  File "/usr0/home/yifanpen/torchaudio_examples/hubert/lightning.py", line 276, in validation_step
    return self._step(batch, batch_idx, "val")[0]
  File "/usr0/home/yifanpen/torchaudio_examples/hubert/lightning.py", line 174, in _step
    logit_m, logit_u, feature_penalty = self.model(
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/torchaudio/models/wav2vec2/model.py", line 215, in forward
    x, mask = self.mask_generator(x, padding_mask)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr0/home/yifanpen/miniconda3/envs/torchaudio_ssl/lib/python3.10/site-packages/torchaudio/models/wav2vec2/components.py", line 967, in forward
    x[mask_indices] = self.mask_embedding
RuntimeError: Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.
```

The reason is that `self.mask_embedding` has a different dtype than `x`: [code here](https://github.com/pytorch/audio/blob/release/0.13/torchaudio/models/wav2vec2/components.py#L966)
A possible solution is to convert `self.mask_embedding` to the same dtype when assigning it to the left-hand side, e.g.:
```
x[mask_indices] = self.mask_embedding.to(x.dtype)
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A5000
GPU 1: NVIDIA RTX A5000
GPU 2: NVIDIA RTX A5000
GPU 3: NVIDIA RTX A5000
GPU 4: NVIDIA RTX A5000
GPU 5: NVIDIA RTX A5000
GPU 6: NVIDIA RTX A5000
GPU 7: NVIDIA RTX A5000

Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] pytorch-lightning==1.8.1
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.10.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.3          py310hd5efca6_1  
[conda] numpy-base                1.23.3          py310h8e6c178_1  
[conda] pytorch                   1.13.0          py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h67b0de4_0    pytorch
[conda] pytorch-lightning         1.8.1                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.13.0              py310_cu117    pytorch
[conda] torchmetrics              0.10.2                   pypi_0    pypi

**Comment by nateanl** [comment]
It's very interesting that amp can't detect `mask_embedding` and auto cast the dtype.
Before we use the solution `x[mask_indices] = self.mask_embedding.to(x.dtype)`, could you try with registering `mask_embedding` in the module? something like `self.register_parameter("mask_embedding", mask_embedding)`, to see if that helps?

**Comment by pyf98** [comment]
I changed it to the following, but still had the same error.
```
# self.mask_embedding = Parameter(torch.FloatTensor(encoder_embed_dim))
self.register_parameter("mask_embedding", Parameter(torch.FloatTensor(encoder_embed_dim)))
```

The PyTorch [documenation](https://pytorch.org/docs/stable/amp.html#cuda-ops-that-promote-to-the-widest-input-type) mentions this op `index_put`. I'm not very sure how this op is handled exactly.

**Comment by pyf98** [comment]
BTW, it might be good to support `amp` training in the provided example if it does not cause numerical issues.

**Comment by nateanl** [comment]
`amp` is supported by default in the current example (https://github.com/pytorch/audio/blob/main/examples/hubert/lightning.py#L250), I set `enabled=False` that's why I didn't notice the embedding dtype issue. I think using the pytorch lightning api is better so that users have a choice to use amp or not.

**Comment by nateanl** [comment]
fixed by #2854
