### ISSUE TITLE
Torchaudio fails to find FFmpeg when installed via poetry

### ISSUE THREAD

**Issue by morganednl** [pytorch/audio#3195]
### 🐛 Describe the bug

I'm using torchaudio in a poetry environment. Since I've upgraded torchaudio from 0.11 to 2.0.1, I need to use ffmpeg as backend to be able to load mp3 files (from Common Voice). My problem is that torchaudio can't find ffmpeg.

```
import torchaudio
print(torchaudio._extension._FFMPEG_INITIALIZED) #False
torchaudio._extension._init_ffmpeg()
```
```
Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "./.venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "./.venv/lib/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/Users/morganedaniel/.pyenv/versions/3.10.4/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(./.venv/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so, 6): Library not loaded: @rpath/libavdevice.58.dylib
  Referenced from: ./.venv/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so
  Reason: image not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./.venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.

```

I've tried to install torchaudio via poetry setting `USE_FFMPEG=1` but got the same error.
The library not found is libavdevice.58.dylib while the libavdevice version on my computer is 59.

Is there a clean way to install torchaudio with ffmpeg via poetry?

Thank you for your help!

### Versions

poetry == 1.3.2
torchaudio == 2.0.1

```
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.30)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
```

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.7.4 (x86_64)
Clang version: 13.0.0 (clang-1300.0.29.30)

Python version: 3.10.4 (main, Mar 21 2023, 19:10:53) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-11.7.4-x86_64-i386-64bit

**Comment by mthrok** [comment]
Hi

What could be happening is that during the build ffmpeg 4 is found and used, but at runtime the said ffmpeg 4 is not found for some reason.

What does the build log says? There  should be a line like [the following](https://github.com/pytorch/audio/actions/runs/4489353483/jobs/7895085404#step:10:239)

```
-- FFMPEG_ROOT=/Users/runner/work/audio/audio/pytorch/audio/third_party/ffmpeg
-- Found FFMPEG: /Users/runner/work/audio/audio/pytorch/audio/third_party/ffmpeg/include (found suitable version "4.1.8", minimum required is "4.1") found components: avdevice avfilter avformat avcodec avutil
```

Can you try specifying `FFMPEG_ROOT` environment variable like above?

**Comment by morganednl** [comment]
I'm using the pre-built binary from pypi so I don't have any build log.
I've installed ffmpeg 4 as required but not sure I used the right configuration to build it. My guess is that I don't understand "how to remove the specific rpath" as specified in the documentation https://pytorch.org/audio/main/installation.html
I've specified `FFMPEG_ROOT` environment variable but I still get the same issue.
