### ISSUE TITLE
mfcc not in torchaudio.compliance.kaldi

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#325]
## 🐛 Bug

When installing using conda:
```
from torchaudio.compliance.kaldi import fbank

# success

from torchaudio.compliance.kaldi import mfcc

# Traceback (most recent call last):
# File "<stdin>", line 1, in <module>
# ImportError: cannot import name 'mfcc' from 'torchaudio.compliance.kaldi' (/home/username/anaconda3/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py)
```

The error does not occur when building from source.

## Environment

From conda:
```
python collect_env.py

Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.15.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0.post2
[pip3] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.14           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] pytorch                   1.3.0                   py3.7_0    pytorch
[conda] torchaudio                0.3.1                      py37    pytorch
```

From source:
```
python collect_env.py 

Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0.post2
[pip3] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.14           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] pytorch                   1.3.0                   py3.7_0    pytorch
[conda] torchaudio                0.4.0a0+8a08c44          pypi_0    pypi
```

**Comment by vincentqb** [comment]
From binaries:
```
conda create -n audio-binary python=3.7
conda activate audio-binary

conda install -c pytorch pytorch
conda install -c pytorch torchaudio

# Test, outside of source folder:
cd
python -c "import torchaudio"
```

From source:
```
conda create -n audio-built python=3.7
conda activate audio-built

conda install -c pytorch pytorch
conda install -c conda-forge sox

python setup.py clean --all
NO_CUDA=1 MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install

# Test, outside of source folder:
cd
python -c "import torchaudio"
```

**Comment by vincentqb** [comment]
[This](https://github.com/pytorch/audio/pull/308#issuecomment-546020394) is how the conda binaries were made.

**Comment by vincentqb** [comment]
Indeed, "torchaudio.compliance.kaldi" in [0.3.1](https://anaconda.org/pytorch/torchaudio/files) does not have mfcc included.

**Comment by vincentqb** [comment]
This also happens when using pip:
```
conda create -n audio-binary python=3.7
conda activate audio-binary

pip install torchaudio
python -c "from torchaudio.compliance.kaldi import mfcc"

# Traceback (most recent call last):
# File "<stdin>", line 1, in <module>
# ImportError: cannot import name 'mfcc' from 'torchaudio.compliance.kaldi' (/home/username/anaconda3/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py)
```

**Comment by vincentqb** [comment]
CC @ezyang

**Comment by mravanelli** [comment]
Thank you!
I had the same problem with MFCC implemented in torchaudio/transforms.py. Did you solve the problem as well?

Best,

Mirco

**Comment by ezyang** [comment]
I don't see what the problem is. 0.3.1 branch doesn't have mfcc in torchaudio.compliance.kaldi (https://github.com/pytorch/audio/blob/master/torchaudio/compliance/kaldi.py). If you want this feature in 0.3 series you'll have to backport the patch. Kaldi mfcc was added in a450cf81c11d206983f209586f38db06e8df2801 (Aug 16), branch cut for 0.3.0 was Jul 30.

**Comment by vincentqb** [comment]
Indeed. I was convinced it had been part of the release. Thanks! I'm closing this issue then.
