### ISSUE TITLE
Failed to write packet (Invalid argument) caused by missing PTS

### ISSUE THREAD

**Issue by whoyao** [pytorch/audio#3311]
### 🐛 Describe the bug

Compared with version 2.0.1, the active branch made major changes to `StreamWriter` in [torchaudio/csrc/ffmpeg/stream_writer](https://github.com/pytorch/audio/tree/main/torchaudio/csrc/ffmpeg/stream_writer). When I used NVIDIA hardware encoders (`h264_nvenc`) to encode flv video streams, I encountered unexpected errors, causing the process to exit.

Snippet to reproduce the error is provided below. 
```python
import os
import shutil
import av
import numpy as np
from fractions import Fraction
import torch
import torchaudio
import torch.nn.functional as F
from torchaudio.io import StreamWriter, StreamReader

VIDEO_FPATH = 'rtmp://xxx.xxx.xxx.xxx/live/test'
VIDEO_URL = 'test.mp4'

video_config = dict(
    frame_rate=25,
    width=256,
    height=256,
    hw_accel='cuda:0',
    encoder='h264_nvenc',
    encoder_format='rgb0',
    encoder_option={'gpu': '0'},
)
stream = StreamWriter(VIDEO_FPATH, format='flv')
stream.add_video_stream(**video_config)
stream.add_audio_stream(sample_rate=44100, num_channels=2, encoder="aac")
stream_handler = stream.open()
streamer = StreamReader(VIDEO_URL)
streamer.add_basic_audio_stream(frames_per_chunk=44100,sample_rate=44100)
streamer.add_basic_video_stream(frames_per_chunk=25,frame_rate=25,width=256,height=256,format="rgb24")

for i, (audio_chunk, frame) in enumerate(streamer.stream()):
    if audio_chunk is not None:
        stream_handler.write_audio_chunk(1, audio_chunk)
    if len(frame.shape) == 3:
        frame = frame.unsqueeze(0)
    frame = F.pad(frame, (0, 0, 0, 0, 0, 1), 'constant', 0)
    stream_handler.write_video_chunk(0, frame.to('cuda:0'))
```
Output:
```
[h264_nvenc @ 0x6802840] Calling dl_fn->cuda_dl->cuCtxPopCurrent(&dummy)
[flv @ 0x68021c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
Traceback (most recent call last):
  File "/workspace/sources/audio-fix/main.py", line 75, in <module>
    stream_handler.write_video_chunk(0, frame.to('cuda:0'))
  File "/workspace/sources/torchaudio/torchaudio/io/_stream_writer.py", line 462, in write_video_chunk
    self._s.write_video_chunk(i, chunk, pts)
RuntimeError: Failed to write packet (Invalid argument).
[aac @ 0x73d4140] Qavg: 3699.658
[aac @ 0x73d4140] 2 frames left in the queue on closing
```
After some investigations, I am sure the error was caused by the following code in ffmpeg, and the error code `EINVAL` corresponds to the information "Invalid argument". 
```c
if (par->codec_id == AV_CODEC_ID_H264 || par->codec_id == AV_CODEC_ID_MPEG4) {
    if (pkt->pts == AV_NOPTS_VALUE) {
        av_log(s, AV_LOG_ERROR, "Packet is missing PTS\n");
        return AVERROR(EINVAL);
    }
}
```
So，I think this problem is caused by missing PTS.

### Versions

**05/04/23 nightly (1e48af0)**

Collecting environment information...
PyTorch version: 2.1.0a0+git979c5b4
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 510.85.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          80
On-line CPU(s) list:             0-79
Thread(s) per core:              1
Core(s) per socket:              40
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
Stepping:                        5
CPU MHz:                         2500.000
BogoMIPS:                        5000.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       2.5 MiB
L1i cache:                       2.5 MiB
L2 cache:                        320 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-39
NUMA node1 CPU(s):               40-79
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni

Versions of relevant libraries:
[pip3] flake8==5.0.4
[pip3] flake8-bugbear==22.9.11
[pip3] flake8-comprehensions==3.10.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.2.4
[pip3] pytorch-msssim==0.2.1
[pip3] pytorch3d==0.7.1
[pip3] torch==2.1.0a0+git979c5b4
[pip3] torchaudio==2.1.0a0+1e48af0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.16.0a0+fc377d0
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.23.1           py39h6c91a56_0
[conda] numpy-base                1.23.1           py39ha15fc14_0
[conda] pytorch-lightning         1.2.4                    pypi_0    pypi
[conda] pytorch-msssim            0.2.1                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch3d                 0.7.1                    pypi_0    pypi
[conda] torch                     2.1.0a0+git979c5b4           dev_0    <develop>
[conda] torchaudio                2.1.0a0+1e48af0           dev_0    <develop>
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.16.0a0+fc377d0           dev_0    <develop>
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by whoyao** [comment]
I have done some testing,  https://github.com/pytorch/audio/pull/3312  may fix this issue.
