### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by YuQing2000** [pytorch/audio#3711]
### ISSUE
When I run 
`python preprocess_lrs3.py --data-dir=D:/BaiduNetdiskDownload/LRS3 --detector=retinaface --dataset=lrs3 --root-dir=D:/pycharmProject/audio_vision/audio-main/examples/avsr/predata --subset=test --seg-duration=16 --groups=4 --job-index=0`
The following appears
`D:\anaconda3\envs\davsr\lib\site-packages\torchaudio\backend\utils.py:62: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Traceback (most recent call last):
  File "preprocess_lrs3.py", line 68, in <module>
    vid_dataloader = AVSRDataLoader(modality="video", detector=args.detector, resize=(96, 96))
  File "D:\pycharmProject\audio_vision\audio-main\examples\avsr\data_prep\data\data_module.py", line 19, in __init__
    self.landmarks_detector = LandmarksDetector(device="cuda:0")
  File "D:\pycharmProject\audio_vision\audio-main\examples\avsr\data_prep\detectors\retinaface\detector.py", line 17, in __init__ 
    self.face_detector = RetinaFacePredictor(
  File "D:\pycharmProject\audio_vision\audio-main\examples\avsr\data_prep\face_detection\ibug\face_detection\retina_face\retina_face_predictor.py", line 28, in __init__
    pretrained_dict = torch.load(model.weights, map_location=self.device)
  File "D:\anaconda3\envs\davsr\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda3\envs\davsr\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
`
May I ask why this problem occurs? How to solve it

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home China
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.27.7
Libc version: N/A

Python version: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
Nvidia driver version: 517.18
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=1992
DeviceID=CPU0
Family=198
L2CacheSize=2048
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=1992
Name=Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main      
[conda] mkl                       2023.1.0         h6b88ed4_46358    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main      
[conda] mkl-service               2.4.0            py38h2bbff1b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main      
[conda] mkl_fft                   1.3.8            py38h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main      
[conda] mkl_random                1.2.4            py38h59b6b97_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main      
[conda] numpy                     1.24.3           py38h79a8e48_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main      
[conda] numpy-base                1.24.3           py38h8a87ada_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main      
[conda] pytorch                   1.13.1          py3.8_cuda11.7_cudnn8_0    pytorch
[conda] pytorch-cuda              11.7                 h16d0643_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.13.1                   pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

**Comment by Kiri0824** [comment]
i found this link: [issues](https://github.com/hhj1897/face_detection/issues/4)  to download the model can solve this!
