### ISSUE TITLE
ModuleNotFoundError: No module named 'torchaudio._ext.th_sox._th_sox'

### ISSUE THREAD

**Issue by drscotthawley** [pytorch/audio#41]
Hi. Even though I've got sox installed, I get a 'module not found' error.  
This is on Mac, with Anaconda & Python 3.6...
```
$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shawley/Downloads/audio/torchaudio/__init__.py", line 9, in <module>
    from ._ext import th_sox
  File "/Users/shawley/Downloads/audio/torchaudio/_ext/th_sox/__init__.py", line 3, in <module>
    from ._th_sox import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'torchaudio._ext.th_sox._th_sox'
>>> 
```
This is after following installation instructions.  
Any suggestions?  Thanks. 

Install log follows below...

```
$ git clone https://github.com/pytorch/audio.git
Cloning into 'audio'...
remote: Counting objects: 304, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 304 (delta 24), reused 19 (delta 10), pack-reused 249
Receiving objects: 100% (304/304), 4.85 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (106/106), done.

$ brew install sox
Error: sox 14.4.2 is already installed
To upgrade to 14.4.2_1, run `brew upgrade sox`

$ brew upgrade sox
==> Upgrading 1 outdated package, with result:
sox 14.4.2 -> 14.4.2_1
==> Upgrading sox 
==> Downloading https://homebrew.bintray.com/bottles/sox-14.4.2_1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sox-14.4.2_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/sox/14.4.2_1: 23 files, 1.8MB

$ pip install cffi
Requirement already satisfied: cffi in /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages (1.11.5)
Requirement already satisfied: pycparser in /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages (from cffi) (2.18)


$ $ python setup.py install
running install
running bdist_egg
running egg_info
creating torchaudio.egg-info
writing torchaudio.egg-info/PKG-INFO
writing dependency_links to torchaudio.egg-info/dependency_links.txt
writing requirements to torchaudio.egg-info/requires.txt
writing top-level names to torchaudio.egg-info/top_level.txt
writing manifest file 'torchaudio.egg-info/SOURCES.txt'
reading manifest file 'torchaudio.egg-info/SOURCES.txt'
writing manifest file 'torchaudio.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.9-x86_64-3.6
creating build/lib.macosx-10.9-x86_64-3.6/torchaudio
copying torchaudio/transforms.py -> build/lib.macosx-10.9-x86_64-3.6/torchaudio
copying torchaudio/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/torchaudio
creating build/lib.macosx-10.9-x86_64-3.6/torchaudio/datasets
copying torchaudio/datasets/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/torchaudio/datasets
copying torchaudio/datasets/yesno.py -> build/lib.macosx-10.9-x86_64-3.6/torchaudio/datasets
copying torchaudio/datasets/vctk.py -> build/lib.macosx-10.9-x86_64-3.6/torchaudio/datasets
creating build/lib.macosx-10.9-x86_64-3.6/torchaudio/_ext
copying torchaudio/_ext/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/torchaudio/_ext
creating build/lib.macosx-10.9-x86_64-3.6/torchaudio/_ext/th_sox
copying torchaudio/_ext/th_sox/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/torchaudio/_ext/th_sox
running build_ext
generating cffi module 'build/temp.macosx-10.9-x86_64-3.6/torchaudio._ext.th_sox._th_sox.c'
creating build/temp.macosx-10.9-x86_64-3.6
building 'torchaudio._ext.th_sox._th_sox' extension
creating build/temp.macosx-10.9-x86_64-3.6/build
creating build/temp.macosx-10.9-x86_64-3.6/build/temp.macosx-10.9-x86_64-3.6
creating build/temp.macosx-10.9-x86_64-3.6/Users
creating build/temp.macosx-10.9-x86_64-3.6/Users/shawley
creating build/temp.macosx-10.9-x86_64-3.6/Users/shawley/Downloads
creating build/temp.macosx-10.9-x86_64-3.6/Users/shawley/Downloads/audio
creating build/temp.macosx-10.9-x86_64-3.6/Users/shawley/Downloads/audio/torchaudio
creating build/temp.macosx-10.9-x86_64-3.6/Users/shawley/Downloads/audio/torchaudio/src
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/shawley/anaconda/envs/py36/include -arch x86_64 -I/Users/shawley/anaconda/envs/py36/include -arch x86_64 -I/Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -Itorchaudio/src -I/Users/shawley/anaconda/envs/py36/include/python3.6m -c build/temp.macosx-10.9-x86_64-3.6/torchaudio._ext.th_sox._th_sox.c -o build/temp.macosx-10.9-x86_64-3.6/build/temp.macosx-10.9-x86_64-3.6/torchaudio._ext.th_sox._th_sox.o
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/shawley/anaconda/envs/py36/include -arch x86_64 -I/Users/shawley/anaconda/envs/py36/include -arch x86_64 -I/Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -Itorchaudio/src -I/Users/shawley/anaconda/envs/py36/include/python3.6m -c /Users/shawley/Downloads/audio/torchaudio/src/th_sox.c -o build/temp.macosx-10.9-x86_64-3.6/Users/shawley/Downloads/audio/torchaudio/src/th_sox.o
In file included from /Users/shawley/Downloads/audio/torchaudio/src/th_sox.c:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateAllTypes.h:10:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateFloatTypes.h:10:
In file included from generic/th_sox.c:1:
torchaudio/src/generic/th_sox.c:11:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (nsamples != -1) {
        ~~~~~~~~ ^  ~~
torchaudio/src/generic/th_sox.c:27:14: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for (x=0; x<samples_read/nchannels; x++) {
            ~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/shawley/Downloads/audio/torchaudio/src/th_sox.c:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateAllTypes.h:10:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateFloatTypes.h:11:
In file included from generic/th_sox.c:1:
torchaudio/src/generic/th_sox.c:11:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (nsamples != -1) {
        ~~~~~~~~ ^  ~~
torchaudio/src/generic/th_sox.c:27:14: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for (x=0; x<samples_read/nchannels; x++) {
            ~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/shawley/Downloads/audio/torchaudio/src/th_sox.c:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateAllTypes.h:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateIntTypes.h:10:
In file included from generic/th_sox.c:1:
torchaudio/src/generic/th_sox.c:11:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (nsamples != -1) {
        ~~~~~~~~ ^  ~~
torchaudio/src/generic/th_sox.c:27:14: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for (x=0; x<samples_read/nchannels; x++) {
            ~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/shawley/Downloads/audio/torchaudio/src/th_sox.c:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateAllTypes.h:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateIntTypes.h:11:
In file included from generic/th_sox.c:1:
torchaudio/src/generic/th_sox.c:11:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (nsamples != -1) {
        ~~~~~~~~ ^  ~~
torchaudio/src/generic/th_sox.c:27:14: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for (x=0; x<samples_read/nchannels; x++) {
            ~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/shawley/Downloads/audio/torchaudio/src/th_sox.c:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateAllTypes.h:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateIntTypes.h:12:
In file included from generic/th_sox.c:1:
torchaudio/src/generic/th_sox.c:11:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (nsamples != -1) {
        ~~~~~~~~ ^  ~~
torchaudio/src/generic/th_sox.c:27:14: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for (x=0; x<samples_read/nchannels; x++) {
            ~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/shawley/Downloads/audio/torchaudio/src/th_sox.c:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateAllTypes.h:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateIntTypes.h:13:
In file included from generic/th_sox.c:1:
torchaudio/src/generic/th_sox.c:11:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (nsamples != -1) {
        ~~~~~~~~ ^  ~~
torchaudio/src/generic/th_sox.c:27:14: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for (x=0; x<samples_read/nchannels; x++) {
            ~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/shawley/Downloads/audio/torchaudio/src/th_sox.c:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateAllTypes.h:11:
In file included from /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateIntTypes.h:14:
In file included from generic/th_sox.c:1:
torchaudio/src/generic/th_sox.c:11:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (nsamples != -1) {
        ~~~~~~~~ ^  ~~
torchaudio/src/generic/th_sox.c:27:14: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
  for (x=0; x<samples_read/nchannels; x++) {
            ~^~~~~~~~~~~~~~~~~~~~~~~
14 warnings generated.
gcc -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/shawley/anaconda/envs/py36/lib -L/Users/shawley/anaconda/envs/py36/lib -headerpad_max_install_names -Wl,-rpath,/Users/shawley/anaconda/envs/py36/lib -L/Users/shawley/anaconda/envs/py36/lib -headerpad_max_install_names -arch x86_64 build/temp.macosx-10.9-x86_64-3.6/build/temp.macosx-10.9-x86_64-3.6/torchaudio._ext.th_sox._th_sox.o build/temp.macosx-10.9-x86_64-3.6/Users/shawley/Downloads/audio/torchaudio/src/th_sox.o -L/Users/shawley/anaconda/envs/py36/lib -lsox -o build/lib.macosx-10.9-x86_64-3.6/torchaudio/_ext/th_sox/_th_sox.abi3.so
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/torchaudio
copying build/lib.macosx-10.9-x86_64-3.6/torchaudio/transforms.py -> build/bdist.macosx-10.9-x86_64/egg/torchaudio
creating build/bdist.macosx-10.9-x86_64/egg/torchaudio/datasets
copying build/lib.macosx-10.9-x86_64-3.6/torchaudio/datasets/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/torchaudio/datasets
copying build/lib.macosx-10.9-x86_64-3.6/torchaudio/datasets/yesno.py -> build/bdist.macosx-10.9-x86_64/egg/torchaudio/datasets
copying build/lib.macosx-10.9-x86_64-3.6/torchaudio/datasets/vctk.py -> build/bdist.macosx-10.9-x86_64/egg/torchaudio/datasets
copying build/lib.macosx-10.9-x86_64-3.6/torchaudio/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/torchaudio
creating build/bdist.macosx-10.9-x86_64/egg/torchaudio/_ext
creating build/bdist.macosx-10.9-x86_64/egg/torchaudio/_ext/th_sox
copying build/lib.macosx-10.9-x86_64-3.6/torchaudio/_ext/th_sox/_th_sox.abi3.so -> build/bdist.macosx-10.9-x86_64/egg/torchaudio/_ext/th_sox
copying build/lib.macosx-10.9-x86_64-3.6/torchaudio/_ext/th_sox/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/torchaudio/_ext/th_sox
copying build/lib.macosx-10.9-x86_64-3.6/torchaudio/_ext/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/torchaudio/_ext
byte-compiling build/bdist.macosx-10.9-x86_64/egg/torchaudio/transforms.py to transforms.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/torchaudio/datasets/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/torchaudio/datasets/yesno.py to yesno.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/torchaudio/datasets/vctk.py to vctk.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/torchaudio/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/torchaudio/_ext/th_sox/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/torchaudio/_ext/__init__.py to __init__.cpython-36.pyc
creating stub loader for torchaudio/_ext/th_sox/_th_sox.abi3.so
byte-compiling build/bdist.macosx-10.9-x86_64/egg/torchaudio/_ext/th_sox/_th_sox.py to _th_sox.cpython-36.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying torchaudio.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying torchaudio.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying torchaudio.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying torchaudio.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying torchaudio.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
torchaudio._ext.th_sox.__pycache__._th_sox.cpython-36: module references __file__
creating dist
creating 'dist/torchaudio-0.1-py3.6-macosx-10.9-x86_64.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing torchaudio-0.1-py3.6-macosx-10.9-x86_64.egg
creating /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torchaudio-0.1-py3.6-macosx-10.9-x86_64.egg
Extracting torchaudio-0.1-py3.6-macosx-10.9-x86_64.egg to /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages
Adding torchaudio 0.1 to easy-install.pth file

Installed /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages/torchaudio-0.1-py3.6-macosx-10.9-x86_64.egg
Processing dependencies for torchaudio==0.1
Searching for cffi==1.11.5
Best match: cffi 1.11.5
Adding cffi 1.11.5 to easy-install.pth file

Using /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages
Searching for pycparser==2.18
Best match: pycparser 2.18
Adding pycparser 2.18 to easy-install.pth file

Using /Users/shawley/anaconda/envs/py36/lib/python3.6/site-packages
Finished processing dependencies for torchaudio==0.1
```

Further poking around:
```
$ cat torchaudio/_ext/th_sox/__init__.py 

from torch.utils.ffi import _wrap_function
from ._th_sox import lib as _lib, ffi as _ffi

__all__ = []
def _import_symbols(locals):
    for symbol in dir(_lib):
        fn = getattr(_lib, symbol)
        if callable(fn):
            locals[symbol] = _wrap_function(fn, _ffi)
        else:
            locals[symbol] = fn
        __all__.append(symbol)

_import_symbols(locals())
```

...I don't see how this is supposed to import other modules from the `th_sox` directory if there's nothing else in there:

```
$ ls torchaudio/_ext/th_sox/
__init__.py      __pycache__/
```
??

**Comment by rivaud** [comment]
Was it the same problem as this issue #1 
You may be trying to import torchaudio in a folder that already contains a folder named torchaudio.
Try changing folder.

**Comment by vincentqb** [comment]
I can't reproduce.

```
brew install sox
# Warning: sox 14.4.2_3 is already installed and up-to-date
# To reinstall 14.4.2_3, run `brew reinstall sox`
conda create -n audio-reinstall python=3.6
conda activate audio-reinstall
conda install pytorch torchvision -c pytorch-nightly
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install

python -c "import torch; import torchaudio;"\
python --version
# Python 3.6.9 :: Anaconda, Inc.
```

You can also try to install sox via `conda`, see [here](https://github.com/pytorch/audio/blob/master/README.md#Dependencies). Please feel free to reopen if you still have this issue.

**Comment by jamarshon** [comment]
@vincentqb Maybe we should encourage people to use the pre-built torchaudio binaries instead of building from source unless they need the newest features 😄. [pip](https://pypi.org/project/torchaudio/),  [conda](https://anaconda.org/pytorch/torchaudio) and [nightlies](https://github.com/pytorch/audio#binaries)
