### ISSUE TITLE
When try to run with Speech2text example : AttributeError: module 'torchaudio' has no attribute 'legacy'

### ISSUE THREAD

**Issue by Nouraaaawwad** [pytorch/audio#451]
## 🐛 Bug

I try the speech to text example in openNMT 
→ python preprocess.py -data_type audio -src_dir data/speech/an4_dataset -train_src data/speech/src-train.txt -train_tgt data/speech/tgt-train.txt -valid_src data/speech/src-val.txt -valid_tgt data/speech/tgt-val.txt -shard_size 300 -save_data data/speech/demo

the error is :
**[2020-03-02 20:21:17,427 INFO] Extracting features...
[2020-03-02 20:21:17,427 INFO]  * number of source features: 0.
[2020-03-02 20:21:17,427 INFO]  * number of target features: 0.
[2020-03-02 20:21:17,427 INFO] Building `Fields` object...
[2020-03-02 20:21:17,428 INFO] Building & saving training data...
[2020-03-02 20:21:17,436 INFO] Building shard 0.
  0% 0/276 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 64, in process_one_shard
    filter_pred=filter_pred
  File "/content/OpenNMT-py/onmt/inputters/dataset_base.py", line 121, in __init__
    for ex_dict in starmap(_join_dicts, zip(*read_iters)):
  File "/content/OpenNMT-py/onmt/inputters/audio_dataset.py", line 127, in read
    spect = self.extract_features(audio_path)
  File "/content/OpenNMT-py/onmt/inputters/audio_dataset.py", line 64, in extract_features
    sound, sample_rate_ = torchaudio.legacy.load(audio_path)
AttributeError: module 'torchaudio' has no attribute 'legacy'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "OpenNMT-py/preprocess.py", line 6, in <module>
    main()
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 293, in main
    preprocess(opt)
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 273, in preprocess
    'train', fields, src_reader, tgt_reader, align_reader, opt)
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 200, in build_save_dataset
    for sub_counter in p.imap(func, shard_iter):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AttributeError: module 'torchaudio' has no attribute 'legacy'**

there was a reply before to make sure if i installed the required torchaudio version specified in requirements.opt.txt. I tried to install it but the page is not found and i install it with **"!pip install torchaudio"** . the same error showing! :((

i am using google colab for runtime.

**Comment by tomassosorio** [comment]
Hey, I would install a later version like for example:
[v0.2.0](https://github.com/pytorch/audio/tree/v0.2.0/torchaudio)

Still as legacy.

**Comment by tomassosorio** [comment]
look into [v0.2.0](https://github.com/pytorch/audio/blob/v0.2.0/torchaudio/legacy.py) legacy is only to load the files.

in [line 64](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/inputters/audio_dataset.py) where the error occurs, you could just change from `torchaudio.legacy.load` to `torchaudio.load`

and probably do a PR to correct that :)

**Comment by Nouraaaawwad** [comment]
yeeeees thank you so much. you solve the problem.

but i got this error :
[2020-03-02 21:37:40,822 INFO] Extracting features...
[2020-03-02 21:37:40,822 INFO]  * number of source features: 0.
[2020-03-02 21:37:40,823 INFO]  * number of target features: 0.
[2020-03-02 21:37:40,823 INFO] Building `Fields` object...
[2020-03-02 21:37:40,823 INFO] Building & saving training data...
[2020-03-02 21:37:40,831 INFO] Building shard 0.
  0% 0/276 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 64, in process_one_shard
    filter_pred=filter_pred
  File "/content/OpenNMT-py/onmt/inputters/dataset_base.py", line 121, in __init__
    for ex_dict in starmap(_join_dicts, zip(*read_iters)):
  File "/content/OpenNMT-py/onmt/inputters/audio_dataset.py", line 127, in read
    spect = self.extract_features(audio_path)
  File "/content/OpenNMT-py/onmt/inputters/audio_dataset.py", line 71, in extract_features
    % (audio_path, sample_rate_, self.sample_rate)
AssertionError: Sample rate of OpenNMT-py/data/speech/an4_dataset/train/wav/1.wav != -sample_rate (48000 vs 16000)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "OpenNMT-py/preprocess.py", line 6, in <module>
    main()
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 293, in main
    preprocess(opt)
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 273, in preprocess
    'train', fields, src_reader, tgt_reader, align_reader, opt)
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 200, in build_save_dataset
    for sub_counter in p.imap(func, shard_iter):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AssertionError: Sample rate of OpenNMT-py/data/speech/an4_dataset/train/wav/1.wav != -sample_rate (48000 vs 16000)

**Comment by tomassosorio** [comment]
Okey, so that is because the sample rate from your files are 48000 and they want 16000 so you have to resample the audio, this could be done in a couple of ways, [using transform resample](https://pytorch.org/audio/transforms.html#torchaudio.transforms.Resample) or using [librosa](https://librosa.github.io/librosa/generated/librosa.core.resample.html?highlight=resample#librosa.core.resample)

For simplicity reasons, I would covert all files using librosa to the desired sample rate 16000 as follows:

```
import librosa
target_sr = 16000
y, sr = librosa.load(audio_path, sr=None)
y_resample = librosa.core.resample(y, sr, target_sr)
librosa.output.write_wav(output_audio_path, y, target_sr)
```

However, this is out of the scope of the issues with torchaudio.

**Comment by Nouraaaawwad** [comment]
thank you soo much tomassosorio, you are genius
