### ISSUE TITLE
Windows build failing in CircleCI

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#488]
As seen for instance [here](https://app.circleci.com/pipelines/github/pytorch/audio/1170/workflows/08c1fb48-7aad-4d9d-a3a7-ee89622e3491/jobs/32311), the windows build in CircleCI has been failing.
```
Traceback (most recent call last):
  File "C:\tools\miniconda3\conda-bld\torchaudio_1585754674449\test_tmp\run_test.py", line 2, in <module>
    import torchaudio
  File "C:\tools\miniconda3\conda-bld\torchaudio_1585754674449\_test_env\lib\site-packages\torchaudio\__init__.py", line 3, in <module>
    import torch
  File "C:\tools\miniconda3\conda-bld\torchaudio_1585754674449\_test_env\lib\site-packages\torch\__init__.py", line 77, in <module>
    ctypes.CDLL(dll)
  File "C:\tools\miniconda3\conda-bld\torchaudio_1585754674449\_test_env\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Tests failed for torchaudio-0.5.0.dev20200401-py36.tar.bz2 - moving package to C:\tools\miniconda3\conda-bld\broken
WARNING:conda_build.build:Tests failed for torchaudio-0.5.0.dev20200401-py36.tar.bz2 - moving package to C:\tools\miniconda3\conda-bld\broken
WARNING conda_build.build:tests_failed(2231): Tests failed for torchaudio-0.5.0.dev20200401-py36.tar.bz2 - moving package to C:\tools\miniconda3\conda-bld\broken
set PREFIX=C:\tools\miniconda3\conda-bld\torchaudio_1585754674449\_test_env
set SRC_DIR=C:\tools\miniconda3\conda-bld\torchaudio_1585754674449\test_tmp

circleci@PACKER-5D4D0A1D %SRC_DIR%>call "%SRC_DIR%\conda_test_env_vars.bat" 

circleci@PACKER-5D4D0A1D %SRC_DIR%>set "CONDA_SHLVL="   && 

circleci@PACKER-5D4D0A1D %SRC_DIR%>conda activate "%PREFIX%" 

(%PREFIX%) circleci@PACKER-5D4D0A1D %SRC_DIR%>IF 0 NEQ 0 exit 1 

(%PREFIX%) circleci@PACKER-5D4D0A1D %SRC_DIR%>"%PREFIX%\python.exe" -s "%SRC_DIR%\run_test.py" 
import: 'torchaudio'

(%PREFIX%) circleci@PACKER-5D4D0A1D %SRC_DIR%>IF 1 NEQ 0 exit 1 
TESTS FAILED: torchaudio-0.5.0.dev20200401-py36.tar.bz2
```

The error appeared first when committing #472 though the PR is seemingly unrelated. As of #419, I would expect even the tests to be green.

We don't yet officially support windows (#425), so, even though this is a regression, this is not blocking the release of 0.5.0.

cc @peterjc123 @seemethere

**Comment by peterjc123** [comment]
@vincentqb It seems that it is picking a CUDA version of binary, which is not able to be imported on a CPU only machine.
