### ISSUE TITLE
Python 3: Last Commit BREAKS usage of DeepSpeech.PyTorch with PyTorch Audio

### ISSUE THREAD

**Issue by dlmacedo** [pytorch/audio#5]
The last commit **BREAKS** using PyTorch Audio with Python 3.

https://github.com/pytorch/audio/commit/f80d6e37386122da2cb3983afad8a5a229571814

```
Traceback (most recent call last):
  File "train.py", line 381, in <module>
    main()
  File "train.py", line 210, in main
    for i, (data) in enumerate(train_loader, start=start_iter):
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 212, in __next__
    return self._process_next_batch(batch)
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 41, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/dlm/code/deepspeech.pytorch/data/data_loader.py", line 159, in __getitem__
    spect = self.parse_audio(audio_path)
  File "/home/dlm/code/deepspeech.pytorch/data/data_loader.py", line 106, in parse_audio
    y = load_audio(audio_path)
  File "/home/dlm/code/deepspeech.pytorch/data/data_loader.py", line 17, in load_audio
    sound, _ = torchaudio.load(path.encode('utf-8'))  # py3 fix
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/torchaudio-0.1-py3.6-linux-x86_64.egg/torchaudio/__init__.py", line 26, in load
    func(bytes(filename, "ascii"), out, sample_rate_p)
TypeError: encoding without a string argument

```

**Comment by dlmacedo** [comment]
https://github.com/pytorch/audio/commit/f80d6e37386122da2cb3983afad8a5a229571814

**Comment by dlmacedo** [comment]
https://github.com/SeanNaren/deepspeech.pytorch/issues/93

**Comment by dlmacedo** [comment]
We need to figure out if we should change Pytorch Audio or DeepSpeeach.Pytorch.

**Comment by SeanNaren** [comment]
This can be closed, been fixed on the deepspeech repo.
