### ISSUE TITLE
Fix TimeStretch Test

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#510]
As noted [here](https://github.com/pytorch/audio/pull/508#issuecomment-608675896), torchscript test for `TimeStretch` is failing on GPU.

**Comment by vincentqb** [comment]
```
assert torch.allclose(jit_out, py_out, atol=1e-2)
```

makes the test green:
```
❯ python test_torchscript_consistency.py -- TestTransforms.test_TimeStretch
Run test with cuda: True
.
----------------------------------------------------------------------
Ran 1 test in 4.676s

OK
```

**Comment by vincentqb** [comment]
This is failing on 0.5.0 branch too.
```
❯ git checkout 7da61a4beeec7b7ff9ff5f1532b2adf99220a9b1
...
❯ python setup.py install
...
❯ python test_transforms.py -- Tester.test_scriptmodule_TimeStretch

Run test with cuda: True
F
======================================================================
FAIL: test_scriptmodule_TimeStretch (__main__.Tester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_transforms.py", line 551, in test_scriptmodule_TimeStretch
    _test_script_module(transforms.TimeStretch, tensor, n_freq=n_freq, hop_length=hop_length, fixed_rate=fixed_rate)
  File "test_transforms.py", line 43, in _test_script_module
    assert torch.allclose(jit_out, py_out)
AssertionError

----------------------------------------------------------------------
Ran 1 test in 4.648s

FAILED (failures=1)
```

**Comment by vincentqb** [comment]
Have you encountered this error @mthrok ?

**Comment by mthrok** [comment]
No, I did not see this and I cannot reproduce this. The test passes in my environment.

**Comment by vincentqb** [comment]
Ok, thanks for confirming.
