### ISSUE TITLE
Backprop support for lfilter

### ISSUE THREAD

**Issue by FBMachine** [pytorch/audio#704]
## 🚀 Feature
It is currently not possible to backpropagate gradients through an lfilter because of this inplace operation:
https://github.com/pytorch/audio/blob/master/torchaudio/functional.py#L661

## Motivation
It's not worth the pytorch overhead to even use lfilter without backprop support (it's much faster when implemented using e.g. numba). When I saw that this was implemented here, I was hoping to use it instead of my own implementation (which is implemented as a custom RNN) as it is honestly too slow.

## Pitch

I would love to see that inplace operation replaced with something that would allow supporting backprop. I'm not sure what the most efficient way to do this is.

## Alternatives

I implemented transposed direct form II digital filters as custom RNNs, but the performance is pretty poor (which seems to be a problem with the fuser). This is the simplest version I tried, which works, but as I said it's quite slow.

```python
class DigitalFilterModel(jit.ScriptModule):
  def __init__(self):
    super(DigitalFilterModel, self).__init__()

  @jit.script_method
  def forward(self, x, coeffs, v1, v2, v3):
    # type: (Tensor, Tensor, Tensor, Tensor, Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor]
    seq_len = x.shape[1]
    output = torch.jit.annotate(List[Tensor], [])
    x = x.unbind(1)
    coeffs = coeffs.unbind(1)
    for i in range(seq_len):
      sample = x[i]
      out = coeffs[0] * sample + v1
      output.append(out)

      v1 = coeffs[1] * sample - coeffs[4] * out + v2
      v2 = coeffs[2] * sample - coeffs[5] * out + v3
      v3 = coeffs[3] * sample - coeffs[6] * out

    return torch.stack(output, 1), v1, v2, v3
```

Another alternative I've used when I only need to backprop through the filter, but not optimize the actual coefficients, is to take advantage of the fact that tanh is close to linear for very small inputs and design a standard RNN to be equivalent to the digital filter. Crushing the input, then rescaling the output to keep it linear gives a result very close to the original filter, but this is obviously quite a hack:

```python
class RNNTDFWrapper(nn.Module):
  def __init__(self, eps=0.000000001):
    super(RNNTDFWrapper, self).__init__()
    self.eps = eps
    self.rnn = nn.RNN(1, 4, 1, False, True)

  def set_coefficients(self, coeffs):
    self.rnn.weight_ih_l0.data[:,:] = torch.tensor(coeffs[:4]).view(-1,1)
    self.rnn.weight_hh_l0.data[:,:] = 0.0
    self.rnn.weight_hh_l0.data[0,1] = 1.0
    self.rnn.weight_hh_l0.data[1,2] = 1.0
    self.rnn.weight_hh_l0.data[2,3] = 1.0
    self.rnn.weight_hh_l0.data[:3,0] = -1.0 * torch.tensor(coeffs[4:])

  def forward(self, x):
    batch_size = x.shape[0]
    x = self.eps * x.view(batch_size, -1, 1)
    x, _ = self.rnn.forward(x)
    x = (1.0/self.eps) * x[:,:,0]
    return x
```

**Comment by mthrok** [comment]
Hi @FBMachine 

Can you provide a snippet that demonstrates `lfilter` not supporting backward?

I was trying to reproduce the issue but putting `lfilter` into `nn.Module` and backprobagating through it seems to work fine, but I might be doing something wrong.

Or, are you saying that you would like to compute gradient for coefficients for `lfilter`?

```python
import torch
import torchaudio.functional as F


class Net(torch.nn.Module):
    def __init__(self, a_coeffs, b_coeffs):
        super().__init__()
        self.a_coeffs = torch.nn.Parameter(a_coeffs, requires_grad=True)
        self.b_coeffs = torch.nn.Parameter(b_coeffs, requires_grad=True)

    def forward(self, x):
        return F.lfilter(x, self.a_coeffs, self.b_coeffs)


def test(device, dtype):
    x = torch.rand(2, 8000, dtype=dtype, device=device, requires_grad=True)
    b_coeffs = torch.tensor([0, 0, 0, 1], dtype=dtype, device=device, requires_grad=True)
    a_coeffs = torch.tensor([1, 0, 0, 0], dtype=dtype, device=device, requires_grad=True)
    net = Net(a_coeffs, b_coeffs).to(device=device, dtype=dtype)
    y = net(x).reshape(-1, 1)
    net.zero_grad()
    y.backward(torch.randn_like(y))
    print('a_grad:', net.a_coeffs.grad)
    print('b_grad:', net.b_coeffs.grad)
    print('x_grad:', x.grad)

for device in ['cpu', 'cuda']:
    for dtype in [torch.float32, torch.float64]:
        print(f'Running {device}, {dtype}')
        test(device, dtype)
```

```bash
$ python foo.py
Running cpu, torch.float32
a_grad: None
b_grad: None
x_grad: tensor([[ 0.2182,  1.3389,  0.0032,  ...,  0.3011,  0.7507,  0.2975],
        [ 0.3733, -1.0556,  0.7375,  ..., -0.7113,  0.9792,  0.3037]])
Running cpu, torch.float64
a_grad: None
b_grad: None
x_grad: tensor([[ 1.7103, -1.2674, -0.5425,  ...,  0.0744, -2.0590,  0.0467],
        [ 0.7821, -0.7788, -0.5301,  ..., -0.3740,  0.6317,  1.7960]],
       dtype=torch.float64)
Running cuda, torch.float32
a_grad: None
b_grad: None
x_grad: tensor([[ 0.2473, -1.0705,  0.9804,  ..., -1.1515, -0.2375, -1.0368],
        [-0.8987, -1.0655,  1.7082,  ...,  0.6394, -0.3092, -0.3852]],
       device='cuda:0')
Running cuda, torch.float64
a_grad: None
b_grad: None
x_grad: tensor([[ 1.9579, -1.0165, -0.5580,  ..., -0.0909,  1.8497, -0.9157],
        [-0.4042, -0.2788,  0.7688,  ..., -0.8789, -0.6830, -0.7406]],
       device='cuda:0', dtype=torch.float64)
```

**Comment by vincentqb** [comment]
Do we know that the derivative is correct though? A check we can do is with [gradcheck](https://pytorch.org/docs/stable/autograd.html#torch.autograd.gradcheck).

**Comment by turian** [comment]
@mthrok Here is a small code example showing that you cannot backprop through an `lfilter` parameter:

```
import torch
import torchaudio
noise = torch.rand(16000)
fp = torch.tensor((440.0), requires_grad=True)
filtered_noise = torchaudio.functional.lowpass_biquad(noise, sample_rate=16000, cutoff_freq=fp)
dist = torch.mean(torch.abs(filtered_noise - noise))
dist.backward(retain_graph=False)
```

gives

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-c658d88b5d27> in <module>
----> 1 dist.backward(retain_graph=False)
      2 print(fp.grad)

/usr/local/lib/python3.8/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    183                 products. Defaults to ``False``.
    184         """
--> 185         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    186 
    187     def register_hook(self, hook):

/usr/local/lib/python3.8/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    123         retain_graph = create_graph
    124 
--> 125     Variable._execution_engine.run_backward(
    126         tensors, grad_tensors, retain_graph, create_graph,
    127         allow_unreachable=True)  # allow_unreachable flag

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by mthrok** [comment]
Hi @turian 

Thanks for the snippet. I confirm that I am seeing the same error.

I updated my previous snippet to use the `lowpass_biquad` and realized that even the forward function does not work.

```pyton
import torch
import torchaudio.functional as F


class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.fp = torch.tensor((440.0), requires_grad=True)

    def forward(self, x):
        return F.lowpass_biquad(x, sample_rate=16000, cutoff_freq=self.fp)


def test(device, dtype):
    net = Net().to(device=device, dtype=dtype)
    x = torch.rand(2, 8000, dtype=dtype, device=device, requires_grad=True)
    y = net(x)
    net.zero_grad()
    y.backward(torch.randn_like(y))
    print('a_grad:', net.a.grad)
    print('b_grad:', net.b.grad)
    print('x_grad:', x.grad)

for device in ['cpu', 'cuda']:
    for dtype in [torch.float32, torch.float64]:
        print(f'Running {device}, {dtype}')
        test(device, dtype)
```

```
Traceback (most recent call last):
  File "bar.py", line 27, in <module>
    test(device, dtype)
  File "bar.py", line 17, in test
    y = net(x)
  File "/home/moto/conda/envs/PY3.8-cuda101/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "bar.py", line 11, in forward
    return F.lowpass_biquad(x, sample_rate=16000, cutoff_freq=self.fp)
  File "/scratch/moto/torchaudio/torchaudio/functional.py", line 703, in lowpass_biquad
    return biquad(waveform, b0, b1, b2, a0, a1, a2)
  File "/scratch/moto/torchaudio/torchaudio/functional.py", line 636, in biquad
    output_waveform = lfilter(
  File "/scratch/moto/torchaudio/torchaudio/functional.py", line 594, in lfilter
    o0.addmv_(windowed_output_signal, a_coeffs_flipped, alpha=-1)
RuntimeError: Output 0 of UnbindBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

**Comment by turian** [comment]
@FBMachine what is the inplace operation in the latest master?

https://github.com/pytorch/audio/blob/5e54c770b41bbdb7b228fe511b364f3f2aa96a88/torchaudio/functional/__init__.py

Can you please copy and paste the offending lines here?

**Comment by turian** [comment]
@FBMachine It appears nnAudio has a lowpass filter that is differentiable:

```
import nnAudio.utils
import torch
from torch.nn.functional import conv1d, fold
lowpass_filter = torch.tensor(nnAudio.utils.create_lowpass_filter(
                                                    band_center = 0.5,
                                                    kernelLength=256,
                                                    transitionBandwidth=0.001
                                                    )
                             )
lowpass_filter = lowpass_filter[None,None,:]
x = torch.rand(10000)[None,None,:]
y = conv1d(x,lowpass_filter,stride=1, padding=(lowpass_filter.shape[-1]-1)//2)
```

**Comment by yoyololicon** [comment]
Hi folks~ I also encounter this issue recently and I want to share my solution.
The approach I chose is to implement a custom autograd function  for `lfilter`.

Here's my implementation :

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchaudio.functional import lfilter as torch_lfilter

from torch.autograd import Function, gradcheck


class lfilter(Function):

    @staticmethod
    def forward(ctx, x, a, b) -> torch.Tensor:
        with torch.no_grad():
            dummy = torch.zeros_like(a)
            dummy[0] = 1

            xh = torch_lfilter(x, a, dummy, False)

            y = xh.view(-1, 1, xh.shape[-1])
            y = F.pad(y, [b.numel() - 1, 0])
            y = F.conv1d(y, b.flip(0).view(1, 1, -1)).view(*xh.shape)

        ctx.save_for_backward(x, a, b, xh)
        return y

    @staticmethod
    def backward(ctx, dy) -> (torch.Tensor, torch.Tensor, torch.Tensor):
        x, a, b, xh = ctx.saved_tensors
        with torch.no_grad():
            dxh = F.conv1d(F.pad(dy.view(-1, 1, dy.shape[-1]), [0, b.numel() - 1]),
                           b.view(1, 1, -1)).view(*dy.shape)

            dummy = torch.zeros_like(a)
            dummy[0] = 1
            dx = torch_lfilter(dxh.flip(-1), a, dummy, False).flip(-1)

            batch = x.numel() // x.shape[-1]
            db = F.conv1d(F.pad(xh.view(1, -1, xh.shape[-1]), [b.numel() - 1, 0]),
                          dy.view(-1, 1, dy.shape[-1]),
                          groups=batch).sum((0, 1)).flip(0)

            da = []
            for i in range(a.numel()):
                dummy[:] = 0
                dummy[i] = -1
                dxhdai = torch_lfilter(xh, a, dummy, False)
                da.append(torch.sum(dxhdai * dxh).view(1, 1))
            da = torch.cat(da).view(-1)

        return dx, da, db
```
The filter form I choose is Direct-Form-II.
I just wrap `torchaudio.functional.lfilter` inside the custom function, no extra dependency is needed. 

Some comparisons between simple for-loop approach and gradient checks: 
https://gist.github.com/yoyololicon/f63f601d62187562070a61377cec9bf8

It has passed the `gradcheck` using a simple 1 pole 1 zero filter model, and I'm planning to do more tests on higher order model.

**Comment by yoyololicon** [comment]
@FBMachine  does it meet your requirement?

**Comment by vincentqb** [comment]
> Hi folks~ I also encounter this issue recently and I want to share my solution.
> The approach I chose is to implement a custom autograd function for `lfilter`.
> 
> Here's my implementation :
> 
> ```python
> import torch
> import torch.nn as nn
> import torch.nn.functional as F
> from torchaudio.functional import lfilter as torch_lfilter
> 
> from torch.autograd import Function, gradcheck
> 
> class lfilter(Function):
> 
>     @staticmethod
>     def forward(ctx, x, a, b) -> torch.Tensor:
>         with torch.no_grad():
>             dummy = torch.zeros_like(a)
>             dummy[0] = 1
> 
>             xh = torch_lfilter(x, a, dummy, False)
> 
>             y = xh.view(-1, 1, xh.shape[-1])
>             y = F.pad(y, [b.numel() - 1, 0])
>             y = F.conv1d(y, b.flip(0).view(1, 1, -1)).view(*xh.shape)
> 
>         ctx.save_for_backward(x, a, b, xh)
>         return y
> 
>     @staticmethod
>     def backward(ctx, dy) -> (torch.Tensor, torch.Tensor, torch.Tensor):
>         x, a, b, xh = ctx.saved_tensors
>         with torch.no_grad():
>             dxh = F.conv1d(F.pad(dy.view(-1, 1, dy.shape[-1]), [0, b.numel() - 1]),
>                            b.view(1, 1, -1)).view(*dy.shape)
> 
>             dummy = torch.zeros_like(a)
>             dummy[0] = 1
>             dx = torch_lfilter(dxh.flip(-1), a, dummy, False).flip(-1)
> 
>             batch = x.numel() // x.shape[-1]
>             db = F.conv1d(F.pad(xh.view(1, -1, xh.shape[-1]), [b.numel() - 1, 0]),
>                           dy.view(-1, 1, dy.shape[-1]),
>                           groups=batch).sum((0, 1)).flip(0)
>             dummy[0] = -1
>             dxhda = torch_lfilter(F.pad(xh, [b.numel() - 1, 0]), a, dummy, False)
>             da = F.conv1d(dxhda.view(1, -1, dxhda.shape[-1]),
>                           dxh.view(-1, 1, dy.shape[-1]),
>                           groups=batch).sum((0, 1)).flip(0)
> 
>         return dx, da, db
> ```
> 
> The filter form I choose is Direct-Form-II.
> I just wrap `torchaudio.functional.lfilter` inside the custom function, no extra dependency is needed.
> 
> Some comparisons between simple for-loop approach and gradient checks:
> https://gist.github.com/yoyololicon/f63f601d62187562070a61377cec9bf8
> 
> It has passed the `gradcheck` using a simple second-order filter model, and I'm planning to do more tests on higher order model.

Thanks for writing this and sharing it with the community! If torchscriptabilitiy is not a concern, then this is a great way to bind the forward and the backward pass :) This is in fact how we (temporarily) bind the prototype RNN transducer [here](https://github.com/pytorch/audio/blob/master/torchaudio/prototype/transducer.py#L14) in torchaudio.

Such custom autograd functions (both in python and C++) are not currently supported by torchscript though. Using this within torchaudio directly in place of the current `lfilter` (which is torchscriptable) would be BC breaking unfortunately. In the long term, we'll need to register the backward pass with autograd. Here's a [tutorial](https://pytorch.org/tutorials/advanced/dispatcher.html#adding-autograd-support) for how to do this in a torchscriptable manner.

**Comment by yoyololicon** [comment]
@vincentqb thanks, I'll take a look.
