### ISSUE TITLE
Automatic batching and torchaudio datasets

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#711]
We need to investigate how we could extend automatic batching for datasets in torchaudio (or vice versa). 

For instance

```python
import torchaudio
import torch
from torchaudio.datasets import YESNO
from torch.utils.data import DataLoader


dataset = YESNO(".", download=True)
data_loader = torch.utils.data.DataLoader(dataset, batch_size=8, shuffle=True, num_workers=8)
for batch in data_loader:
    print(len(batch))
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-b4b430c698c6> in <module>
      7 dataset = YESNO(".", download=True)
      8 data_loader = torch.utils.data.DataLoader(dataset, batch_size=8, shuffle=True, num_workers=8)
----> 9 for batch in data_loader:
     10     print(len(batch))

~/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    854             else:
    855                 del self._task_info[idx]
--> 856                 return self._process_data(data)
    857 
    858     def _try_put_index(self):

~/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
    879         self._try_put_index()
    880         if isinstance(data, ExceptionWrapper):
--> 881             data.reraise()
    882         return data
    883 

~/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    392             # (https://bugs.python.org/issue2651), so we work around it.
    393             msg = KeyErrorMessage(msg)
--> 394         raise self.exc_type(msg)

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/private/home/vincentqb/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/private/home/vincentqb/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/private/home/vincentqb/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/private/home/vincentqb/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/private/home/vincentqb/anaconda3/envs/audio-built/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 48880 and 49440 in dimension 2 at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/TH/generic/THTensor.cpp:612
```

One workaround is to explicitly define a collate function:

```python
import torchaudio
import torch
from torchaudio.datasets import YESNO
from torch.utils.data import DataLoader


def collate_fn(batch):

    tensors = [b[0].t() for b in batch if b]
    tensors = torch.nn.utils.rnn.pad_sequence(tensors, batch_first=True)
    tensors = tensors.transpose(1, -1)

    targets = torch.tensor([b[2] for b in batch if b])
    targets = torch.nn.utils.rnn.pad_sequence(targets, batch_first=True)

    return tensors, targets


dataset = YESNO(".", download=True)
data_loader = torch.utils.data.DataLoader(dataset, batch_size=8, shuffle=True, num_workers=8, collate_fn=collate_fn)
for batch, labels in data_loader:
    print(batch.shape, labels.shape)
```

**Comment by mthrok** [comment]
Closing the issue as mechanism around I/O, preprocessing and batching are discussed and addressed in PyTorch core as a part of dataset redesign.
