### ISSUE TITLE
soundfile backend missing

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#837]
After installing torchaudio through conda on linux:
```python
Python 3.8.5 | packaged by conda-forge | (default, Jul 24 2020, 01:25:15) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchaudio
>>> torchaudio.set_audio_backend("soundfile")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/vincentqb/anaconda3/envs/pytorch/lib/python3.8/site-packages/torchaudio/backend/utils.py", line 40, in set_audio_backend
    raise RuntimeError(
RuntimeError: Backend "soundfile" is not one of available backends: ['sox', 'sox_io'].
>>> torchaudio.__version__
'0.6.0a0+f17ae39'
```

cc @mthrok

**Comment by mthrok** [comment]
Soundfile is optional dependency so not installed automatically. Please run `conda install pysoundfile -c conda-forge`.

**Comment by vincentqb** [comment]
indeed, oops :)
