### ISSUE TITLE
torchaudio import error

### ISSUE THREAD

**Issue by zyn2609530** [pytorch/audio#878]
## To Reproduce

Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/liuzuozhen/tools/anaconda/anaconda3/lib/python3.7/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension
  File "/storage/liuzuozhen/tools/anaconda/anaconda3/lib/python3.7/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/storage/liuzuozhen/tools/anaconda/anaconda3/lib/python3.7/site-packages/torchaudio/extension/extension.py", line 12, in _init_extension
    _init_script_module(ext)
  File "/storage/liuzuozhen/tools/anaconda/anaconda3/lib/python3.7/site-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
AttributeError: module 'torch' has no attribute 'classes'

## Environment
 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux):Ubuntu 5.4.0
 - How you installed PyTorch (`conda`, `pip`, source): conda install
 - Build command you used (if compiling from source):
 - Python version:Python 3.7.4
 - CUDA/cuDNN version: cuda 9.0
 - GPU models and configuration:
 - Any other relevant information:

**Comment by mthrok** [comment]
Hi @zyn2609530 

Your PyTorch version is too old. Please checkout [README](https://github.com/pytorch/audio#dependencies) for the corresponding PyTorch / torchaudio versions.
