### ISSUE TITLE
CircleCI failing

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#929]
We are experiencing CircleCI errors on master that look flaky, e.g. [here](https://app.circleci.com/pipelines/github/pytorch/audio/3455/workflows/dda668b7-25c3-48e9-bccc-d8a2c7fd6338). Thoughts on resolving them? I'm opening this issue so we can keep track of them.

**Comment by vincentqb** [comment]
I see two errors on windows that are not the usual dependency mismatch on [master](https://app.circleci.com/pipelines/github/pytorch/audio), see [here](https://app.circleci.com/pipelines/github/pytorch/audio/3574/workflows/e67bc63a-8ed6-4aa9-aa54-c6539264e9cb/jobs/105253) and [here](https://app.circleci.com/pipelines/github/pytorch/audio/3574/workflows/e67bc63a-8ed6-4aa9-aa54-c6539264e9cb/jobs/105256).

```
+ PATH='/c/tools/miniconda3:/c/tools/miniconda3/Library/mingw-w64/bin:/c/tools/miniconda3/Library/usr/bin:/c/tools/miniconda3/Library/bin:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/python3.8:/c/tools/miniconda3/envs/python3.8/Library/mingw-w64/bin:/c/tools/miniconda3/envs/python3.8/Library/usr/bin:/c/tools/miniconda3/envs/python3.8/Library/bin:/c/tools/miniconda3/envs/python3.8/Scripts:/c/tools/miniconda3/envs/python3.8/bin:/c/tools/miniconda3/Scripts/condabin:/c/Program Files (x86)/Windows Application Driver:/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin:/c/Program Files (x86)/Microsoft Visual Studio/Installer:/c/tools/ruby26:/c/tools/ruby26/bin:/c/ProgramData/nvm:/c/tools/miniconda3:/c/tools/miniconda3/Library/mingw-w64/bin:/c/tools/miniconda3/Library/usr/bin:/c/tools/miniconda3/Library/bin:/c/tools/miniconda3/Scripts:/c/miniconda3/miniconda3/condabin:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/ProgramData/GooGet:/c/Program Files/Google/Compute Engine/metadata_scripts:/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:/c/Program Files/PowerShell/7:/c/Program Files/Google/Compute Engine/sysprep:/c/Program Files/Docker:/c/ProgramData/chocolatey/bin:/c/Program Files/Git/cmd:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin:/c/Program Files/Git LFS:/c/Program Files/Amazon/AWSCLI/bin:/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code:/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager:/c/Program Files (x86)/vim/vim80:/c/Go/bin:/c/Program Files/OpenJDK/jdk-12.0.2/bin:/c/ProgramData/nvm:/c/Program Files/nodejs:/c/Program Files/dotnet:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/IncrediBuild:/c/Users/Default/AppData/Local/Microsoft/WindowsApps:/c/Users/Default/go/bin:/c/Users/Default/.dotnet/tools:/c/Users/circleci/AppData/Local/Microsoft/WindowsApps'
+ export PATH
+ /c/tools/miniconda3/Scripts/conda.exe install -v -y
Traceback (most recent call last):
  File "C:\tools\miniconda3\lib\site-packages\conda\exceptions.py", line 1003, in __call__
    return func(*args, **kwargs)
  File "C:\tools\miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\tools\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\tools\miniconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "C:\tools\miniconda3\lib\site-packages\conda\cli\install.py", line 217, in install
    raise CondaValueError("too few arguments, "
conda.exceptions.CondaValueError: too few arguments, must supply command line package specs or --file
```

**Comment by vincentqb** [comment]
@mthrok -- I see the same errors on `release/0.7` branch [here](https://github.com/pytorch/audio/commits/release/0.7). Thoughts?

**Comment by mthrok** [comment]
> @mthrok -- I see the same errors on `release/0.7` branch [here](https://github.com/pytorch/audio/commits/release/0.7). Thoughts?

The link you posted is not pointing any CI job, so I do not know which one you are mentioning. When I checked `release/0.7` yesterday, the only failing jobs were macOS unittests.

**Comment by vincentqb** [comment]
Oops, the release indeed looks fine, thanks for giving a second pair of eyes @mthrok :) Since I don't see the error in the release and the original issue reported above is fixed, I'll close this issue.

**Comment by mthrok** [comment]
> Oops, the release indeed looks fine, 

@vincentqb Where did you look at? I am having hard time finding CI jobs for release branch.

**Comment by vincentqb** [comment]
I was really just looking at the last time they ran in the list of commits from the release [here](https://github.com/pytorch/audio/commits/release/0.7). The last they ran was for #896.
