### ISSUE TITLE
[JIT] scripting torchaudio.transforms.MFCC() error 

### ISSUE THREAD

**Issue by qute012** [pytorch/audio#991]
Hi. I face problem when i use torchaudio.transforms.MFCC() as preprocessing on android app. Help ME

---version---
pytorch::1.7.0
torchaudio::0.7.0

Add gradle dependencies

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.github.zagum:SpeechRecognitionView:1.2.2'
    //implementation 'org.pytorch:pytorch_android:1.4.0'
    //implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android:1.7.0'
}
```

scripting from nn.Module 
```
mfcc = torchaudio.transforms.MFCC()
scripted.save("./mfcc.pt")
```

When Module implements on android's java code, it doesn't work, Module forward function don't recognize forward in script.
errors:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.real_time_speech_command, PID: 17200
    com.facebook.jni.CppException: Method 'forward' is not defined.
    Exception raised from get_method at ../../../../src/main/cpp/libtorch_include/x86/torch/csrc/jit/api/object.h:91 (most recent call first):
    (no backtrace available)
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:48)
        at com.example.real_time_speech_command.MainActivity.startRecognition(MainActivity.java:224)
        at com.example.real_time_speech_command.MainActivity.access$400(MainActivity.java:48)
        at com.example.real_time_speech_command.MainActivity$2.onClick(MainActivity.java:184)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by mthrok** [comment]
Hi @qute012 

Is this specific to MFCC? What happens if you use other transforms?

**Comment by qute012** [comment]
Hi @mthrok 

When i use Spectrogram,
```
spec = torchaudio.transforms.Spectrogram(n_fft=512)
sm = torch.jit.script(spec)
sm.save("./spec.pt")
```

The error is below.
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.real_time_speech_command, PID: 18810
    java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/torchaudio/transforms.py", line 15, in forward
        waveform: Tensor) -> Tensor:
        _0 = __torch__.torchaudio.functional.spectrogram
        _1 = _0(waveform, 0, self.window, 512, 256, 512, 2., False, )
             ~~ <--- HERE
        return _1
      File "code/__torch__/torchaudio/functional.py", line 17, in spectrogram
      shape = torch.size(waveform0)
      waveform2 = torch.reshape(waveform0, [-1, shape[-1]])
      spec_f = __torch__.torch.functional.stft(waveform2, n_fft, hop_length, win_length, window, True, "reflect", False, True, None, )
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      _1 = torch.slice(shape, 0, -1, 1)
      _2 = torch.slice(torch.size(spec_f), -3, 9223372036854775807, 1)
      File "code/__torch__/torch/functional.py", line 21, in stft
      else:
        input0 = input
      _2 = torch.stft(input0, n_fft, hop_length, win_length, window, normalized, onesided, return_complex)
           ~~~~~~~~~~ <--- HERE
      return _2
    
    Traceback of TorchScript, original code (most recent call last):
      File "/home/cilab/.local/lib/python3.6/site-packages/torchaudio/transforms.py", line 83, in forward
                Fourier bins, and time is the number of window hops (n_frame).
            """
            return F.spectrogram(waveform, self.pad, self.window, self.n_fft, self.hop_length,
                   ~~~~~~~~~~~~~ <--- HERE
                                 self.win_length, self.power, self.normalized)
      File "/home/cilab/.local/lib/python3.6/site-packages/torch/functional.py", line 516, in stft
            input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
            input = input.view(input.shape[-signal_dim:])
        return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
               ~~~~~~~~ <--- HERE
                        normalized, onesided, return_complex)
    RuntimeError: fft: ATen not compiled with MKL support
    
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:48)
        at com.example.real_time_speech_command.MainActivity.startRecognition(MainActivity.java:224)
        at com.example.real_time_speech_command.MainActivity.access$400(MainActivity.java:48)
        at com.example.real_time_speech_command.MainActivity$2.onClick(MainActivity.java:184)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by mthrok** [comment]
> Hi @mthrok
> 
> When i use Spectrogram,
> 
> ```
> spec = torchaudio.transforms.Spectrogram(n_fft=512)
> sm = torch.jit.script(spec)
> sm.save("./spec.pt")
> ```
> 
> The error is below.
> 

@qute012 

Looks like that setup is not correct. The JIT object is generated in the environment where the underlying implementation is MKL-based and the Android environment does not have MKL. I do not work on Android so I am not sure how this can be fixed, but I guess either using PyTorch without MKL or using an Android binary with MKL would be the right direction.

**Comment by qute012** [comment]
@mthrok 
Thank you for response.
